import { CommissariatData } from "@/app/types";

export const COMMISSARIAT_DATA: Record<string, CommissariatData> = {
  unair: {
    slug: "unair",
    name: "GenBI Komisariat UNAIR",
    university: "Universitas Airlangga",
    logo_univ: "/assets/logos/unair.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI Komisariat UNAIR merupakan wadah bagi penerima beasiswa Bank Indonesia di Universitas Airlangga untuk berkarya, mengabdi, dan berkontribusi bagi pengembangan ekonomi dan sosial masyarakat, khususnya di lingkungan kampus dan Surabaya.",
    socials: { instagram: "@genbi_unair", email: "genbiunair@gmail.com" },
    bph: [
      {
        role: "Ketua Umum",
        name: "Nama Ketua UNAIR",
        image: "/assets/images/individu.jpg",
        university: "Universitas Airlangga",
        major: "Jurusan",
        instagram: "@user",
        linkedin: "user",
      },
      // ... (other BPH members would go here, kept truncated for brevity/mock)
    ],
    divisions: [],
    proker: [
      {
        id: "unair-1",
        title: "Sosialisasi Beasiswa BI",
        slug: "unair-sosialisasi-beasiswa",
        commissariat: "UNAIR",
        type: "Sosialisasi",
        audience: "External",
        status: "Completed",
        date: "01 Feb 2025",
        dateIso: "2025-02-01",
        location: "Aula UNAIR",
        format: "Offline",
        description:
          "Kegiatan sosialisasi beasiswa Bank Indonesia kepada mahasiswa baru.",
        description_long:
          "PROKER INI TELAH TERLAKSANA. Kegiatan ini bertujuan untuk memberikan informasi mendalam mengenai proses seleksi Beasiswa Bank Indonesia. Dihadiri oleh lebih dari 200 mahasiswa, acara ini berjalan lancar dan antusiasme peserta sangat tinggi.",
        objectives: [
          "Meningkatkan awareness mahasiswa tentang Beasiswa BI",
          "Memberikan tips lolos seleksi berkas & wawancara",
          "Memperkenalkan komunitas GenBI kepada publik",
        ],
        benefits: [
          "Mahasiswa paham alur pendaftaran",
          "Meningkatnya jumlah pendaftar berkualitas",
          "Branding GenBI semakin kuat",
        ],
        gallery: [
          "/assets/images/raker.jpg",
          "/assets/images/bnsp.JPG",
          "/assets/images/background.jpg",
        ],
        documentation: "https://instagram.com/genbi_unair", // Link Added
        newsUrl: "https://unair.ac.id/news",
      },
      {
        id: "unair-2",
        title: "GenBI Mengajar",
        slug: "unair-genbi-mengajar",
        commissariat: "UNAIR",
        type: "Social",
        audience: "External",
        status: "On-going",
        date: "20 Feb 2025",
        dateIso: "2025-02-20",
        location: "SDN 1 Surabaya",
        format: "Offline",
        description:
          "Program pengabdian masyarakat berupa pengajaran di sekolah dasar binaan.",
      },
      {
        id: "unair-3",
        title: "Bersih-Bersih Pantai",
        slug: "unair-bersih-pantai",
        commissariat: "UNAIR",
        type: "Social",
        audience: "External",
        status: "Upcoming",
        date: "15 Mar 2025",
        dateIso: "2025-03-15",
        location: "Pantai Kenjeran",
        format: "Offline",
        description: "Aksi kepedulian lingkungan di pantai kenjeran.",
      },
      // Past Events (Simulated)
      {
        id: "unair-4",
        title: "GenBI Leadership Camp 2024",
        slug: "unair-leadership-camp",
        commissariat: "UNAIR",
        type: "Training",
        audience: "Internal",
        status: "Completed",
        date: "10 Des 2024",
        dateIso: "2024-12-10",
        format: "Offline",
        description: "Pelatihan kepemimpinan untuk pengurus baru GenBI UNAIR.",
      },
      {
        id: "unair-5",
        title: "Seminar Nasional Ekonomi Digital",
        slug: "unair-seminar-ekonomi",
        commissariat: "UNAIR",
        type: "Seminar",
        audience: "External",
        status: "Completed",
        date: "25 Agu 2024",
        dateIso: "2024-08-25",
        format: "Hybrid",
        description: "Seminar membahas potensi ekonomi digital di Jawa Timur.",
      },
      {
        id: "unair-6",
        title: "Bakti Sosial Ramadhan",
        slug: "unair-baksos-ramadhan",
        commissariat: "UNAIR",
        type: "Social",
        audience: "External",
        status: "Completed",
        date: "10 Apr 2024",
        dateIso: "2024-04-10",
        format: "Offline",
        description: "Berbagi takjil dan santunan anak yatim.",
      },
    ],
    awardees: [],
    documents: [
      // 2025 Documents
      {
        id: 1,
        title: "SK Pengurus GenBI UNAIR 2025",
        type: "SK",
        fileType: "PDF",
        size: "2.1 MB",
        date: "15 Jan 2025",
      },
      {
        id: 2,
        title: "Proposal GenBI Mengajar 2025",
        type: "Proposal",
        fileType: "PDF",
        size: "5.4 MB",
        date: "10 Feb 2025",
      },
      // 2024 Documents
      {
        id: 11,
        title: "Laporan Pertanggungjawaban (LPJ) 2024",
        type: "LPJ",
        fileType: "PDF",
        size: "15.2 MB",
        date: "30 Des 2024",
      },
      {
        id: 12,
        title: "Dokumentasi Rakorwil 2024",
        type: "Dokumentasi",
        fileType: "ZIP",
        size: "45.0 MB",
        date: "20 Nov 2024",
      },
      {
        id: 13,
        title: "SK Penerima Beasiswa BI 2024",
        type: "SK",
        fileType: "PDF",
        size: "1.8 MB",
        date: "10 Jan 2024",
      },
      // 2023 Documents
      {
        id: 21,
        title: "LPJ GenBI UNAIR Periode 2023",
        type: "LPJ",
        fileType: "PDF",
        size: "12.5 MB",
        date: "28 Des 2023",
      },
      {
        id: 22,
        title: "Modul Sosialisasi QRIS 2023",
        type: "Materi",
        fileType: "PPTX",
        size: "8.2 MB",
        date: "15 Agt 2023",
      },
      {
        id: 23,
        title: "Data Awardee 2023",
        type: "Data",
        fileType: "XLSX",
        size: "500 KB",
        date: "05 Feb 2023",
      },
      // 2022 Documents
      {
        id: 31,
        title: "Arsip Foto Kegiatan 2022",
        type: "Dokumentasi",
        fileType: "ZIP",
        size: "120 MB",
        date: "31 Des 2022",
      },
      {
        id: 32,
        title: "SK Pengurus 2022",
        type: "SK",
        fileType: "PDF",
        size: "2.0 MB",
        date: "12 Jan 2022",
      },
      // 2021 Documents
      {
        id: 41,
        title: "Laporan Akhir Tahun 2021",
        type: "LPJ",
        fileType: "PDF",
        size: "10.1 MB",
        date: "29 Des 2021",
      },
      {
        id: 42,
        title: "Pedoman GenBI Jatim 2021",
        type: "SOP",
        fileType: "PDF",
        size: "3.5 MB",
        date: "01 Mar 2021",
      },
    ],
  },
  unesa: {
    slug: "unesa",
    name: "GenBI Komisariat UNESA",
    university: "Universitas Negeri Surabaya",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UNESA berdedikasi untuk menjadi garda terdepan dalam edukasi QRIS dan kebijakan Bank Indonesia di lingkungan pendidikan.",
    socials: { instagram: "@genbi_unesa", email: "genbiunesa@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "unesa-1",
        title: "Sosialisasi QRIS",
        slug: "unesa-sosialisasi-qris",
        commissariat: "UNESA",
        type: "Sosialisasi",
        audience: "External",
        status: "Completed",
        date: "01 Feb 2025",
        dateIso: "2025-02-01",
        format: "Offline",
        description: "Sosialisasi QRIS kepada pedagang kantin kampus.",
      },
      {
        id: "unesa-2",
        title: "GenBI Goes to School",
        slug: "unesa-goes-to-school",
        commissariat: "UNESA",
        type: "Education",
        audience: "External",
        status: "Upcoming",
        date: "10 May 2025",
        dateIso: "2025-05-10",
        format: "Offline",
        description: "Edukasi kebanksentralan ke SMA di Surabaya.",
      },
      // Past Events (Simulated)
      {
        id: "unesa-3",
        title: "Webinar Investasi Cerdas",
        slug: "unesa-webinar-investasi",
        commissariat: "UNESA",
        type: "Webinar",
        audience: "External",
        status: "Completed",
        date: "15 Nov 2024",
        dateIso: "2024-11-15",
        format: "Online",
        description: "Webinar tentang literasi keuangan dan investasi bagi mahasiswa.",
      },
      {
        id: "unesa-4",
        title: "GenBI Peduli Lingkungan",
        slug: "unesa-peduli-lingkungan",
        commissariat: "UNESA",
        type: "Social",
        audience: "External",
        status: "Completed",
        date: "20 Jun 2023",
        dateIso: "2023-06-20",
        format: "Offline",
        description: "Aksi tanam pohon di Taman Bungkul.",
      },
    ],
    awardees: [],
    documents: [
      {
        id: 101,
        title: "LPJ GenBI UNESA 2024",
        type: "LPJ",
        fileType: "PDF",
        size: "12.2 MB",
        date: "25 Des 2024",
      },
      {
        id: 102,
        title: "Dokumentasi Sosialisasi QRIS 2024",
        type: "Dokumentasi",
        fileType: "ZIP",
        size: "85 MB",
        date: "15 Okt 2024",
      },
    ],
  },
  "upn-veteran-jatim": {
    slug: "upn-veteran-jatim",
    name: "GenBI Komisariat UPN Veteran Jatim",
    university: "UPN Veteran Jawa Timur",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UPN Jatim aktif dalam pengembangan UMKM dan digitalisasi ekonomi di sekitar kampus.",
    socials: { instagram: "@genbiupnvjt", email: "genbiupn@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "upn-1",
        title: "Pendampingan UMKM",
        slug: "upn-pendampingan-umkm",
        commissariat: "UPNVJT",
        type: "Economic",
        audience: "External",
        status: "On-going",
        date: "Every Weekend",
        dateIso: "2025-01-01", // Placeholder
        format: "Offline",
        description: "Mendampingi UMKM dalam pencatatan keuangan digital.",
      },
      {
        id: "upn-2",
        title: "Seminar Bela Negara",
        slug: "upn-seminar-bela-negara",
        commissariat: "UPNVJT",
        type: "Seminar",
        audience: "External",
        status: "Completed",
        date: "20 Jan 2025",
        dateIso: "2025-01-20",
        format: "Offline",
        description: "Seminar gabungan wawasan kebangsaan dan ekonomi.",
      },
      {
        id: "upn-3",
        title: "Workshop Digital Marketing UMKM",
        slug: "upn-workshop-digital-marketing",
        commissariat: "UPNVJT",
        type: "Workshop",
        audience: "External",
        status: "Completed",
        date: "10 Okt 2024",
        dateIso: "2024-10-10",
        format: "Offline",
        description: "Pelatihan pemasaran digital untuk pelaku UMKM binaan.",
      },
    ],
    awardees: [],
    documents: [
      {
        id: 201,
        title: "Proposal Seminar Bela Negara",
        type: "Proposal",
        fileType: "PDF",
        size: "3.5 MB",
        date: "05 Jan 2025",
      },
    ],
  },
  its: {
    slug: "its",
    name: "GenBI Komisariat ITS",
    university: "Institut Teknologi Sepuluh Nopember",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI ITS fokus pada inovasi teknologi finansial dan digitalisasi layanan publik.",
    socials: { instagram: "@genbi_its", email: "genbiits@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "its-1",
        title: "Hackathon Fintech",
        slug: "its-hackathon-fintech",
        commissariat: "ITS",
        type: "Competition",
        audience: "External",
        status: "Upcoming",
        date: "20 Jun 2025",
        dateIso: "2025-06-20",
        format: "Offline",
        description: "Kompetisi ide solusi fintech untuk mahasiswa.",
      },
      {
        id: "its-2",
        title: "Pelatihan Data Science",
        slug: "its-pelatihan-data-science",
        commissariat: "ITS",
        type: "Training",
        audience: "Internal",
        status: "Completed",
        date: "05 Mar 2025",
        dateIso: "2025-03-05",
        format: "Online",
        link: "https://zoom.us",
        description: "Pelatihan pengolahan data ekonomi.",
      },
      // Past Events (Simulated)
      {
        id: "its-3",
        title: "Workshop Fintech 101",
        slug: "its-workshop-fintech",
        commissariat: "ITS",
        type: "Workshop",
        audience: "External",
        status: "Completed",
        date: "10 Nov 2024",
        dateIso: "2024-11-10",
        format: "Offline",
        description: "Pengenalan teknologi finansial untuk mahasiswa umum.",
      },
      {
        id: "its-4",
        title: "GenBI Coding Camp",
        slug: "its-coding-camp",
        commissariat: "ITS",
        type: "Training",
        audience: "Internal",
        status: "Completed",
        date: "15 Jul 2023",
        dateIso: "2023-07-15",
        format: "Hybrid",
        description: "Bootcamp pemrograman intensif selama 3 hari.",
      },
    ],
    awardees: [],
    documents: [
      {
        id: 301,
        title: "Modul Pelatihan Data Science",
        type: "Materi",
        fileType: "PDF",
        size: "5.5 MB",
        date: "01 Mar 2025",
      },
      {
        id: 302,
        title: "Dokumentasi Hackathon 2024",
        type: "Dokumentasi",
        fileType: "ZIP",
        size: "200 MB",
        date: "10 Des 2024",
      },
    ],
  },
  uinsa: {
    slug: "uinsa",
    name: "GenBI Komisariat UINSA",
    university: "UIN Sunan Ampel Surabaya",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UINSA mengintegrasikan nilai-nilai ekonomi syariah dalam setiap program kerjanya.",
    socials: { instagram: "@genbi_uinsa", email: "genbiuinsa@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "uinsa-1",
        title: "Festival Ekonomi Syariah",
        slug: "uinsa-festival-ekonomi-syariah",
        commissariat: "UINSA",
        type: "Festival",
        audience: "External",
        status: "Upcoming",
        date: "10 Aug 2025",
        dateIso: "2025-08-10",
        format: "Offline",
        description: "Pameran produk halal dan talkshow ekonomi syariah.",
      },
      {
        id: "uinsa-2",
        title: "Kajian Ekonomi Islam",
        slug: "uinsa-kajian-ekonomi-islam",
        commissariat: "UINSA",
        type: "Kajian",
        audience: "External",
        status: "On-going",
        date: "Monthly",
        dateIso: "2025-01-10",
        format: "Hybrid",
        description: "Diskusi rutin isu ekonomi terkini perspektif Islam.",
      },
      // Past Events (Simulated)
      {
        id: "uinsa-3",
        title: "Seminar Wakaf Produktif",
        slug: "uinsa-seminar-wakaf",
        commissariat: "UINSA",
        type: "Seminar",
        audience: "External",
        status: "Completed",
        date: "20 Okt 2024",
        dateIso: "2024-10-20",
        format: "Offline",
        description: "Optimalisasi wakaf untuk kesejahteraan umat.",
      },
      {
        id: "uinsa-4",
        title: "Pelatihan Kewirausahaan Syariah",
        slug: "uinsa-pelatihan-wirausaha",
        commissariat: "UINSA",
        type: "Training",
        audience: "External",
        status: "Completed",
        date: "05 Mei 2024",
        dateIso: "2024-05-05",
        format: "Offline",
        description: "Membangun bisnis berkah dengan prinsip syariah.",
      },
    ],
    awardees: [],
    documents: [],
  },
  unugiri: {
    slug: "unugiri",
    name: "GenBI Komisariat UNUGIRI",
    university: "UNU Sunan Giri Bojonegoro",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UNUGIRI hadir untuk memberdayakan ekonomi pedesaan dan pesantren.",
    socials: { instagram: "@genbi_unugiri", email: "genbiunugiri@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "unugiri-1",
        title: "Pesantren Go Digital",
        slug: "unugiri-pesantren-go-digital",
        commissariat: "UNUGIRI",
        type: "Education",
        audience: "External",
        status: "On-going",
        date: "Weekly",
        dateIso: "2025-02-01",
        format: "Offline",
        description: "Edukasi pembayaran digital di koperasi pesantren.",
      },
      // Past Events (Simulated)
      {
        id: "unugiri-2",
        title: "Sosialisasi Qris di Pasar Tradisional",
        slug: "unugiri-sosialisasi-pasar",
        commissariat: "UNUGIRI",
        type: "Sosialisasi",
        audience: "External",
        status: "Completed",
        date: "12 Des 2024",
        dateIso: "2024-12-12",
        format: "Offline",
        description: "Turun ke pasar memberdayakan pedagang dengan QRIS.",
      },
    ],
    awardees: [],
    documents: [],
  },
  utm: {
    slug: "utm",
    name: "GenBI Komisariat UTM",
    university: "Universitas Trunojoyo Madura",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UTM fokus pada pengembangan potensi pariwisata dan ekonomi garam di Madura.",
    socials: { instagram: "@genbi_utm", email: "genbiutm@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "utm-1",
        title: "Promosi Wisata Madura",
        slug: "utm-promosi-wisata-madura",
        commissariat: "UTM",
        type: "Promotion",
        audience: "External",
        status: "Upcoming",
        date: "12 Sep 2025",
        dateIso: "2025-09-12",
        format: "Offline",
        description: "Konten kreatif promosi wisata lokal.",
      },
      // Past Events (Simulated)
      {
        id: "utm-2",
        title: "Festival Garam Madura",
        slug: "utm-festival-garam",
        commissariat: "UTM",
        type: "Festival",
        audience: "External",
        status: "Completed",
        date: "15 Sep 2024",
        dateIso: "2024-09-15",
        format: "Offline",
        description: "Mengangkat potensi garam lokal ke pasar nasional.",
      },
    ],
    awardees: [],
    documents: [],
  },
  pens: {
    slug: "pens",
    name: "GenBI Komisariat PENS",
    university: "Politeknik Elektronika Negeri Surabaya",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI PENS siap menciptakan inovasi teknologi tepat guna untuk UMKM binaan Bank Indonesia.",
    socials: { instagram: "@genbi_pens", email: "genbipens@gmail.com" },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "pens-1",
        title: "Alat Ketahanan Pangan IoT",
        slug: "pens-alat-ketahanan-pangan",
        commissariat: "PENS",
        type: "Research",
        audience: "Internal",
        status: "On-going",
        date: "Jul 2025",
        dateIso: "2025-07-01",
        format: "Hybrid",
        description: "Riset alat bantu pertanian berbasis IoT.",
      },
      // Past Events (Simulated)
      {
        id: "pens-2",
        title: "Pelatihan IoT untuk UMKM",
        slug: "pens-pelatihan-iot",
        commissariat: "PENS",
        type: "Training",
        audience: "External",
        status: "Completed",
        date: "20 Nov 2024",
        dateIso: "2024-11-20",
        format: "Offline",
        description: "Pemanfaatan teknologi sederhana untuk efisiensi produksi.",
      },
    ],
    awardees: [],
    documents: [],
  },
  "uin-madura": {
    slug: "uin-madura",
    name: "GenBI Komisariat UIN Madura",
    university: "UIN Madura",
    logo_univ: "/assets/logos/genbi.svg",
    logo_genbi: "/assets/logos/genbi.svg",
    cover_image: "/assets/images/raker.jpg",
    description:
      "GenBI UIN Madura aktif mensosialisasikan cinta, bangga, dan paham rupiah di kalangan santri.",
    socials: {
      instagram: "@genbi_uinmadura",
      email: "genbiuinmadura@gmail.com",
    },
    bph: [],
    divisions: [],
    proker: [
      {
        id: "uinmadura-1",
        title: "CBP Rupiah Goes to Pondok",
        slug: "uinmadura-cbp-rupiah",
        commissariat: "UIN Madura",
        type: "Education",
        audience: "External",
        status: "Completed",
        date: "15 Jan 2025",
        dateIso: "2025-01-15",
        format: "Offline",
        description: "Sosialisasi CBP Rupiah di Ponpes Pamekasan.",
      },
      // Past Events (Simulated)
      {
        id: "uinmadura-2",
        title: "GenBI Mengabdi Desa",
        slug: "uinmadura-mengabdi-desa",
        commissariat: "UIN Madura",
        type: "Social",
        audience: "External",
        status: "Completed",
        date: "10 Jun 2024",
        dateIso: "2024-06-10",
        format: "Offline",
        description: "Bakti sosial dan edukasi di desa binaan.",
      },
    ],
    awardees: [],
    documents: [],
  },
};
