export interface DocumentItem {
  id: number;
  title: string;
  category: "Template" | "Panduan" | "SOP" | "Materi" | "Laporan";
  type: "DOCX" | "PDF" | "PPTX" | "XLSX" | "PSD";
  size: string;
  date: string;
}

export const DOCUMENTS_DATA: DocumentItem[] = [
  {
    id: 1,
    title: "Template Surat Peminjaman Tempat",
    category: "Template",
    type: "DOCX",
    size: "245 KB",
    date: "2024-01-15",
  },
  {
    id: 2,
    title: "Template Surat Undangan Pemateri",
    category: "Template",
    type: "DOCX",
    size: "180 KB",
    date: "2024-01-20",
  },
  {
    id: 3,
    title: "Panduan Laporan Pertanggungjawaban (LPJ)",
    category: "Panduan",
    type: "PDF",
    size: "1.2 MB",
    date: "2023-12-10",
  },
  {
    id: 4,
    title: "SOP Media Sosial GenBI Jatim",
    category: "SOP",
    type: "PDF",
    size: "3.5 MB",
    date: "2023-11-05",
  },
  {
    id: 5,
    title: "Template Proposal Kegiatan",
    category: "Template",
    type: "DOCX",
    size: "500 KB",
    date: "2024-02-01",
  },
  {
    id: 6,
    title: "Materi Leadership Camp Day 1",
    category: "Materi",
    type: "PDF",
    size: "5.2 MB",
    date: "2023-12-11",
  },
  {
    id: 7,
    title: "Materi Leadership Camp Day 2",
    category: "Materi",
    type: "PDF",
    size: "4.8 MB",
    date: "2023-12-12",
  },
  {
    id: 8,
    title: "Template Sertifikat Peserta",
    category: "Template",
    type: "PPTX",
    size: "2.1 MB",
    date: "2024-02-10",
  },
  {
    id: 9,
    title: "Panduan Pengajuan Beasiswa 2024",
    category: "Panduan",
    type: "PDF",
    size: "890 KB",
    date: "2024-01-01",
  },
  {
    id: 10,
    title: "Laporan Kegiatan Bersih Pantai",
    category: "Laporan",
    type: "PDF",
    size: "3.2 MB",
    date: "2023-10-20",
  },
  {
    id: 11,
    title: "SOP Administrasi Kesekretariatan",
    category: "SOP",
    type: "PDF",
    size: "1.5 MB",
    date: "2023-09-15",
  },
  {
    id: 12,
    title: "Template Press Release Kegiatan",
    category: "Template",
    type: "DOCX",
    size: "120 KB",
    date: "2024-02-15",
  },
  {
    id: 13,
    title: "Materi Workshop Public Speaking",
    category: "Materi",
    type: "PPTX",
    size: "8.5 MB",
    date: "2023-11-20",
  },
  {
    id: 14,
    title: "Laporan Tahunan GenBI 2023",
    category: "Laporan",
    type: "PDF",
    size: "12.5 MB",
    date: "2023-12-30",
  },
  {
    id: 15,
    title: "Template RAB Kegiatan",
    category: "Template",
    type: "XLSX",
    size: "45 KB",
    date: "2024-01-10",
  },
  {
    id: 16,
    title: "Panduan Desain Grafis GenBI",
    category: "Panduan",
    type: "PDF",
    size: "5.6 MB",
    date: "2023-10-05",
  },
  {
    id: 17,
    title: "SOP Keuangan dan Bendahara",
    category: "SOP",
    type: "PDF",
    size: "2.1 MB",
    date: "2023-09-01",
  },
  {
    id: 18,
    title: "Template Surat Tugas Anggota",
    category: "Template",
    type: "DOCX",
    size: "110 KB",
    date: "2024-02-05",
  },
  {
    id: 19,
    title: "Materi Kebanksentralan BI",
    category: "Materi",
    type: "PDF",
    size: "3.4 MB",
    date: "2023-11-15",
  },
  {
    id: 20,
    title: "Laporan Kegiatan Sosialisasi QRIS",
    category: "Laporan",
    type: "PDF",
    size: "2.8 MB",
    date: "2023-11-25",
  },
  {
    id: 21,
    title: "Template Absensi Peserta",
    category: "Template",
    type: "XLSX",
    size: "30 KB",
    date: "2024-01-25",
  },
  {
    id: 22,
    title: "Panduan Mengelola Website Komisariat",
    category: "Panduan",
    type: "PDF",
    size: "1.8 MB",
    date: "2023-10-15",
  },
  {
    id: 23,
    title: "SOP Publikasi Media",
    category: "SOP",
    type: "PDF",
    size: "1.3 MB",
    date: "2023-09-10",
  },
  {
    id: 24,
    title: "Materi Kewirausahaan Digital",
    category: "Materi",
    type: "PPTX",
    size: "6.7 MB",
    date: "2023-12-05",
  },
  {
    id: 25,
    title: "Template MoMT Rapat Bulanan",
    category: "Template",
    type: "DOCX",
    size: "150 KB",
    date: "2024-02-20",
  },
  {
    id: 26,
    title: "Laporan Keuangan Semester 1",
    category: "Laporan",
    type: "PDF",
    size: "4.2 MB",
    date: "2023-07-15",
  },
  {
    id: 27,
    title: "Panduan Penulisan Artikel Berita",
    category: "Panduan",
    type: "PDF",
    size: "950 KB",
    date: "2023-10-25",
  },
  {
    id: 28,
    title: "Template ID Card Panitia",
    category: "Template",
    type: "PSD",
    size: "15 MB",
    date: "2024-01-05",
  },
  {
    id: 29,
    title: "SOP Peminjaman Inventaris",
    category: "SOP",
    type: "PDF",
    size: "1.1 MB",
    date: "2023-09-20",
  },
  {
    id: 30,
    title: "Materi Personal Branding",
    category: "Materi",
    type: "PDF",
    size: "2.9 MB",
    date: "2023-12-15",
  },
  {
    id: 31,
    title: "Laporan Evaluasi Program Kerja",
    category: "Laporan",
    type: "PDF",
    size: "3.5 MB",
    date: "2023-12-20",
  },
  {
    id: 32,
    title: "Template Surat Balasan Kerjasama",
    category: "Template",
    type: "DOCX",
    size: "160 KB",
    date: "2024-02-25",
  },
];
