import { ProkerData } from "@/app/types";

export const SHARED_EVENTS: ProkerData[] = [
  {
    id: 1,
    title: "GenBI Jatim Leadership Camp",
    slug: "genbi-jatim-leadership-camp",
    commissariat: "Wilayah (Jatim)",
    type: "Training",
    audience: "Internal",
    status: "Completed",
    date: "10 Des 2024",
    dateIso: "2024-12-10",
    time: "08:00 - 17:00",
    location: "Hotel Batu, Malang",
    format: "Offline",
    description:
      "Kegiatan pelatihan kepemimpinan intensif untuk seluruh anggota baru GenBI Jawa Timur.",
    description_long:
      "GenBI Jatim Leadership Camp adalah program unggulan tahunan yang dirancang khusus untuk membekali anggota baru dengan soft-skill kepemimpinan, manajemen organisasi, dan wawasan kebanksentralan. \n\nSelama 3 hari 2 malam, peserta digembleng melalui sesi materi dari expert, simulasi Focus Group Discussion (FGD), dan outbound yang melatih kekompakan. Kegiatan ini menjadi gerbang utama internalisasi nilai-nilai GenBI yaitu Dedikasi, Prestasi, dan Kontribusi.",
    objectives: [
      "Membangun karakter kepemimpinan yang tangguh dan adaptif.",
      "Mempererat bonding antar anggota dari berbagai komisariat kampus.",
      "Meningkatkan pemahaman tentang tugas dan fungsi Bank Indonesia.",
    ],
    kpi: ["500 Peserta", "90% Tingkat Kepuasan", "100% Kehadiran"],
    impact: ["Peningkatan skill leadership", "Solidaritas angkatan"],
    benefits: [
      "Sertifikat tingkat provinsi.",
      "Networking dengan 500+ mahasiswa berprestasi se-Jatim.",
      "Pengembangan skill public speaking dan critical thinking.",
    ],
    evaluation: "Acara berjalan lancar, perlu perbaikan di manajemen waktu.",
    gallery: [
      "/assets/images/galeri/1.jpg",
      "/assets/images/galeri/2.jpg",
      "/assets/images/galeri/3.jpg",
    ],
    documentation:
      "https://drive.google.com/drive/folders/12_kAqqvQKFkqvJDEjCAds_ZVcdNskO2h?usp=drive_link",
    lpjLink: "#",
    proposalLink: "#",
    newsUrl: "/news/genbi-jatim-leadership-camp",
  },
  {
    id: 5,
    title: "GenBI Ambassador",
    slug: "genbi-ambassador",
    commissariat: "Wilayah (Jatim)",
    type: "Competition",
    audience: "Internal",
    status: "On-going",
    date: "15 Jan 2025",
    dateIso: "2025-01-15",
    time: "09:00 - 16:00",
    location: "Surabaya",
    format: "Offline",
    description:
      "Pemilihan duta GenBI untuk menjadi wajah dan representasi public speaking komunitas.",
    description_long:
      "Ajang pencarian bakat duta GenBI yang akan bertugas selama satu periode. Peserta akan melewati tahap seleksi administrasi, wawancara, tes bakat, dan karantina.",
    objectives: [
      "Menemukan ikon GenBI yang komunikatif.",
      "Branding organisasi.",
    ],
    kpi: ["50 Pendaftar", "Terpilih Putra & Putri GenBI"],
    impact: ["Meningkatkan citra GenBI di mata publik"],
    benefits: ["Sash & Crown", "Uang Pembinaan", "Spotlight Media"],
    gallery: ["/assets/images/galeri/1.jpg"],
  },
  {
    id: 6,
    title: "Website Development",
    slug: "website-development",
    commissariat: "Wilayah (Jatim)",
    type: "Project",
    audience: "Internal",
    status: "On-going",
    date: "01 Jan 2025",
    dateIso: "2025-01-01",
    time: "Flexible",
    location: "Online",
    format: "Online",
    description:
      "Pengembangan platform digital terintegrasi untuk database dan publikasi kegiatan.",
    description_long:
      "Proyek pembuatan website resmi GenBI Jatim sebagai pusat informasi, database anggota, dan showcase karya.",
    objectives: ["Digitalisasi database.", "Pusat informasi satu pintu."],
    benefits: ["Skill Coding", "Portofolio IT"],
    gallery: ["/assets/images/galeri/2.jpg"],
  },
  {
    id: 7,
    title: "Ge-Nius (GenBI in Us)",
    slug: "ge-nius",
    commissariat: "Wilayah (Jatim)",
    type: "Program",
    audience: "External",
    status: "Recurring",
    date: "25 Jan 2025",
    dateIso: "2025-01-25",
    time: "Monthly",
    location: "Instagram",
    format: "Online",
    description:
      "Program rutin bulanan untuk mengapresiasi capaian anggota GenBI Jatim di berbagai bidang.",
    description_long:
      "Ge-Nius (GenBI in Us) adalah inisiatif Divisi PR-Medkom untuk memantik semangat berprestasi. Setiap akhir bulan, kami mengkurasi dan mempublikasikan capaian anggota—mulai dari juara lomba, publikasi ilmiah, hingga partisipasi event internasional—dalam format visual yang estetik di Instagram.",
    objectives: [
      "Membangun budaya apresiasi yang suportif.",
      "Database prestasi anggota GenBI Jatim.",
      "Branding positif media sosial organisasi.",
    ],
    benefits: [
      "Fitur eksklusif di Instagram GenBI Jatim.",
      "Sertifikat Elektronik 'Member of the Month'.",
      "Poin keaktifan tambahan.",
    ],
    gallery: ["/assets/images/galeri/3.jpg"],
  },
  {
    id: 2,
    title: "Rapat Koordinasi Wilayah (Rakorwil)",
    slug: "rakorwil-2025",
    commissariat: "Wilayah (Jatim)",
    type: "Rapat",
    audience: "Internal",
    status: "On-going",
    date: "10 Feb 2025",
    dateIso: "2025-02-10",
    time: "09:00 - 15:00",
    location: "Zoom Meeting",
    format: "Online",
    link: "https://zoom.us/j/123",
    description:
      "Forum diskusi strategis antar ketua komisariat se-Jawa Timur untuk penyelarasan program kerja.",
    description_long:
      "Rakorwil merupakan forum legislatif tertinggi di tingkat wilayah yang mempertemukan seluruh Ketua Komisariat dan Badan Pengurus Harian (BPH) GenBI Koordinator Komisariat Jawa Timur. \n\nAgenda utama meliputi evaluasi kinerja triwulanan, penyelarasan Rencana Anggaran Biaya (RAB), dan penetapan kalender kegiatan terpadu untuk satu periode ke depan. Forum ini memastikan setiap komisariat berjalan dalam satu visi yang sama.",
    objectives: [
      "Menyelaraskan agenda kerja antar komisariat.",
      "Mengevaluasi kendala dan tantangan di setiap kampus.",
      "Merumuskan strategi kolaborasi lintas komisariat.",
    ],
    benefits: [
      "Terciptanya kalender kegiatan yang terintegrasi.",
      "Solusi taktis untuk permasalahan organisasi.",
    ],
    gallery: [],
  },
  {
    id: 3,
    title: "GenBI Jatim Award 2025",
    slug: "genbi-jatim-award-2025",
    commissariat: "Wilayah (Jatim)",
    type: "Awarding",
    audience: "Internal",
    status: "Upcoming",
    date: "20 Mei 2025",
    dateIso: "2025-05-20",
    location: "Grand City Surabaya",
    format: "Offline",
    description:
      "Ajang penghargaan bagi komisariat, divisi, dan anggota dengan kinerja terbaik periode ini.",
    description_long:
      "Malam penganugerahan bergengsi untuk mengapresiasi kerja keras dan dedikasi seluruh elemen GenBI Jawa Timur. \n\nTerdapat berbagai kategori nominasi mulai dari 'The Most Active Commissariat', 'Best Social Project', hingga 'Male & Female of The Year'. Acara ini juga dimeriahkan dengan penampilan seni dari bakat-bakat terbaik anggota GenBI.",
    objectives: [
      "Memberikan apresiasi kepada anggota dan komisariat berprestasi.",
      "Memotivasi peningkatan kualitas kinerja organisasi.",
      "Menjadi ajang selebrasi dan silaturahmi akbar.",
    ],
    benefits: [
      "Trophy dan sertifikat penghargaan eksklusif.",
      "Eksposur prestasi di media sosial GenBI Jatim.",
    ],
    gallery: [],
  },
  {
    id: 8,
    title: "GenBI Mengajar",
    slug: "genbi-mengajar",
    commissariat: "Wilayah (Jatim)",
    type: "Social",
    audience: "External",
    status: "Upcoming",
    date: "15 Jun 2025",
    dateIso: "2025-06-15",
    location: "SDN 1 Surabaya",
    format: "Offline",
    description:
      "Program pengabdian masyarakat fokus pada literasi keuangan sejak dini di SD sekitar Surabaya.",
    description_long: "Kegiatan edukatif yang menyenangkan...",
    objectives: ["Meningkatkan literasi."],
    benefits: ["Pengalaman mengajar."],
    gallery: [],
  },
  {
    id: 9,
    title: "Bersih Pantai Kenjeran",
    slug: "bersih-pantai-kenjeran",
    commissariat: "Wilayah (Jatim)",
    type: "Social",
    audience: "External",
    status: "Upcoming",
    date: "10 Jul 2025",
    dateIso: "2025-07-10",
    location: "Pantai Kenjeran",
    format: "Offline",
    description:
      "Aksi nyata peduli lingkungan dengan membersihkan sampah plastik di area wisata.",
    description_long: "Kolaborasi dengan dinas kebersihan...",
    objectives: ["Lingkungan bersih."],
    benefits: ["Sertifikat Relawan."],
    gallery: [],
  },
  {
    id: 10,
    title: "UMKM Digital Fest",
    slug: "umkm-digital-fest",
    commissariat: "Wilayah (Jatim)",
    type: "Event",
    audience: "External",
    status: "Upcoming",
    date: "05 Agu 2025",
    dateIso: "2025-08-05",
    location: "Tunjungan Plaza",
    format: "Offline",
    description: "Workshop dan pameran produk UMKM binaan Bank Indonesia.",
    description_long: "Mendorong digitalisasi pembayaran QRIS...",
    objectives: ["Support UMKM."],
    benefits: ["Networking bisnis."],
    gallery: [],
  },
  {
    id: 11,
    title: "GenBI Esport Tournament",
    slug: "genbi-esport-tournament",
    commissariat: "Wilayah (Jatim)",
    type: "Competition",
    audience: "External",
    status: "Upcoming",
    date: "20 Sep 2025",
    dateIso: "2025-09-20",
    location: "Online",
    format: "Online",
    description: "Turnamen persahabatan Mobile Legends antar komisariat.",
    description_long: "Membangun kekompakan melalui hobi...",
    objectives: ["Bonding fun."],
    benefits: ["Hadiah menarik."],
    gallery: [],
  },
  {
    id: 12,
    title: "Webinar Beasiswa 2026",
    slug: "webinar-beasiswa-2026",
    commissariat: "Wilayah (Jatim)",
    type: "Webinar",
    audience: "External",
    status: "Upcoming",
    date: "15 Okt 2025",
    dateIso: "2025-10-15",
    location: "Zoom",
    format: "Online",
    description:
      "Sosialisasi pembukaan pendaftaran beasiswa BI periode selanjutnya.",
    description_long: "Tips dan trik lolos seleksi...",
    objectives: ["Regenerasi anggota."],
    benefits: ["Info eksklusif."],
    gallery: [],
  },
];
