export const prokerPensData = [
  {
    "divisi": "EKRAF",
    "nama_proker": "SIP QRIS",
    "tanggal": "-",
    "format": "Offline",
    "status": "Cancel",
    "deskripsi": "Sosialisasi Qris terhadap masyarakat yang dikunjungi saat proker genbi mancing",
    "kpi": "Keberhasilan program secara kuantitas ditargetkan dengan mengunjungi minimal 10 UMKM di beberapa titik wilayah Pulau Bawean, memberikan sosialisasi kepada minimal 10 pelaku UMKM, serta melibatkan 10 anggota GenBI PENS dalam kegiatan keliling. Dari sisi kualitas, targetnya adalah meningkatnya pemahaman UMKM mengenai manfaat dan cara penggunaan QRIS berdasarkan observasi, terlaksananya pendampingan yang membantu UMKM mempraktikkan penggunaan QRIS secara mandiri, serta terwujudnya peran peserta sebagai frontliner, agent of change, and future leader dalam mendorong digitalisasi ekonomi lokal",
    "dampak": "-",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "EKRAF",
    "nama_proker": "Pengadaan Identitas GENBI PENS",
    "tanggal": "contoh: Minggu, 10 Januari 2026 - 1 Februari 2026",
    "format": "Online",
    "status": "Done",
    "deskripsi": "Program ini merupakan upaya memperkuat identitas dan kekompakan anggota GenBI melalui pengadaan jaket. Kegiatan dimulai dengan survei kebutuhan dan preferensi anggota (desain, bahan, ukuran), dilanjutkan dengan perancangan desain sesuai pedoman visual Bank Indonesia. Proses selanjutnya meliputi pemilihan vendor berdasarkan kualitas dan harga, pengecekan kualitas produksi, hingga distribusi jaket kepada seluruh anggota agar GenBI PENS tampil lebih kredibel dan mudah dikenali",
    "kpi": "Tolok ukur keberhasilan secara kuantitas meliputi terselenggaranya survei kebutuhan dengan partisipasi minimal 80% anggota, terpilihnya satu desain final hasil voting, serta produksi dan distribusi jaket kepada 100% anggota sesuai ukuran yang diajukan dan tepat waktu. Secara kualitas, diharapkan terwujud identitas organisasi yang lebih jelas and seragam, meningkatnya rasa kebersamaan and profesionalitas, serta jaket memenuhi standar kualitas and desain sesuai pedoman Bank Indonesia untuk meningkatkan citra organisasi saat kegiatan internal maupun eksternal.",
    "dampak": "Meningkatnya citra, kredibilitas, rasa kebersamaan, dan kebanggaan anggota GenBI PENS.",
    "evaluasi": "Partisipasi anggota yang berkeinginan untuk pengadaan identitas GenBi PENS tidak banyak",
    "dokumentasi": "Jaket",
    "lpj": "Tidak ada LPJ",
    "keterangan": ""
  },
  {
    "divisi": "KESMA",
    "nama_proker": "Aksi Sehat : Check UP Kesehatan (genBi Mancing)",
    "tanggal": "-",
    "format": "Offline",
    "status": "Cancel",
    "deskripsi": "Program “Aksi Sehat: Check Up Kesehatan” adalah merupakan salah satu bentuk kegiatan promotif dan preventif dalam bidang kesehatan yang dirancang untuk meningkatkan kesadaran masyarakat, khususnya masyarakat, mengenai pentingnya pemantauan kondisi kesehatan secara berkala. Melalui kegiatan ini, peserta diberikan kesempatan untuk melakukan pemeriksaan kesehatan dasar meliputi pemeriksaan tekanan darah, indeks massa tubuh (BMI).",
    "kpi": "TUK KUANTITAS: \n1. Tujuh anggota divisi KESMA aktif dalam kegiatan\n2. 20 peserta kegiatan MANCING mendapatkan Check up  kesehatan dan mendapatkan vitamin\nTUK KUALITAS: \n1. Pengecekan Berat badan dan Tinggi badan\n2. Seluruh panitia telah diberikan briefing dan role assignment\n3. Minimal 80% peserta puas dengan pelayanan",
    "dampak": "-",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "KESMA",
    "nama_proker": "Aksi Sehat: Berbagi Makanan Bergizi (genBi BASO)",
    "tanggal": "2026-03-15",
    "format": "Offline",
    "status": "Done",
    "deskripsi": "Program “Aksi Sehat: Berbagi Makanan Bergizi” adalah kegiatan berbagi paket makanan bergizi kepada anak-anak panti asuhan untuk membantu memenuhi kebutuhan nutrisi mereka sekaligus meningkatkan kepedulian sosial masyarakat. Kegiatan ini dirancang dengan standar gizi seimbang dan pelaksanaan yang higienis agar manfaatnya terasa optimal bagi penerima.",
    "kpi": "TUK KUANTITAS: \n1. Tujuh anggota divisi KESMA aktif dalam kegiatan\n2. Total 100% peserta kegiatan BASO mendapatkan paket makanan bergizi\nTUK KUALITAS: \n1. Menu makanan memenuhi rekomendasi porsi seimbang\n2. Proses memasak mematuhi standar higiene\n3. Min 85% anak-anak dan pengurus panti merasa puas dengan rasa, porsi, dan kebermanfaatan.",
    "dampak": "Meningkatnya status nutrisi anak panti melalui makanan bergizi seimbang serta terbangunnya kepedulian sosial yang tinggi di kalangan anggota GenBI PENS.",
    "evaluasi": "Seluruh target kuantitas terpenuhi dengan partisipasi aktif anggota. Untuk kedepannya, perlu diperhatikan variasi menu agar lebih menarik bagi anak-anak dan koordinasi waktu distribusi agar makanan tetap dalam kondisi hangat saat diterima.",
    "dokumentasi": "GENBI BASO 2026",
    "lpj": "LPJ LHS GENBI PENS 26.pdf",
    "keterangan": ""
  },
  {
    "divisi": "MEDFO",
    "nama_proker": "Video Kreatif (Kegiatan GenBI Mancing)",
    "tanggal": "-",
    "format": "Offline",
    "status": "Cancel",
    "deskripsi": "Program “Video Kreatif Kegiatan GenBI Mancing” bertujuan untuk mengabadikan dan mempromosikan rangkaian kegiatan GenBI Mancing melalui karya video yang dibuat langsung oleh para peserta. Video berdurasi maksimal 5 menit ini berisi momen kebersamaan, edukasi, serta nilai positif dari kegiatan, lalu diunggah melalui reels Instagram pribadi peserta. Program ini dirancang untuk meningkatkan kreativitas, memperluas jangkauan publikasi acara, dan memperkuat engagement antar anggota GenBI melalui media digital yang menarik dan informatif.",
    "kpi": "1. 50% peserta GenBI Mancing mengunggah video kreatif di Instagram.\n2. Minimal 1 video dari setiap kelompok/rombongan.\n3. Total engagement minimal 300 interaksi dari seluruh unggahan peserta.",
    "dampak": "1. Meningkatkan eksposur kegiatan GenBI Mancing di media sosial.\n2. Mengembangkan kreativitas dan kemampuan storytelling peserta.\n3. Memperkuat citra positif GenBI melalui konten visual yang menarik.\n4. Menjadi dokumentasi publik yang mudah diakses dan dibagikan.",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "MEDFO",
    "nama_proker": "Konten Edukasi",
    "tanggal": "desember 2025 - januari 2026",
    "format": "Online",
    "status": "Done",
    "deskripsi": "Konten Edukasi adalah program pembuatan konten informatif dalam bentuk postingan feed atau video yang membahas materi seputar GenBI, Bank Indonesia, literasi keuangan, serta pengetahuan umum yang relevan bagi anggota dan masyarakat. Program ini dilaksanakan secara kolaborasi dengan Divisi Penkraf (Pendidikan Kreatif) untuk memastikan kualitas konten tetap menarik, kreatif, dan sesuai identitas visual GenBI. Konten dipublikasikan melalui akun Instagram GenBI PENS sebagai upaya meningkatkan literasi, memperluas jangkauan edukasi, dan memperkuat branding GenBI di media sosial.",
    "kpi": "1.Mengunggah 2 konten edukasi setiap minggu.\n2. Engagement rata-rata ≥200 interaksi per konten.\n3. Peningkatan jumlah pengikut Instagram GenBI PENS sebesar 5% per bulan.\n4. Kolaborasi aktif dengan divisi Penkraf dalam setiap tahap produksi.",
    "dampak": "1. Meningkatkan literasi anggota dan publik tentang BI dan keuangan.\n2. Meningkatkan citra profesional dan kreatif GenBI PENS.\n3. Mendorong kerja sama antardivisi, khususnya Divisi Penkraf.\n4. Menambah jangkauan audiens dan interaksi akun GenBI.",
    "evaluasi": "konten kurang rutin",
    "dokumentasi": "Video Edukasi",
    "lpj": "tidak ada lpj",
    "keterangan": ""
  },
  {
    "divisi": "LINGKUNGAN HIDUP DAN SOSIAL",
    "nama_proker": "GenBI Mancing",
    "tanggal": "-",
    "format": "Offline",
    "status": "Cancel",
    "deskripsi": "GenBI Mancing merupakan kegiatan aksi peduli lingkungan yang berfokus pada pembersihan Pantai Delegan, edukasi lingkungan, serta peningkatan literasi ekonomi dan kesehatan bagi masyarakat pesisir. Kegiatan ini menggabungkan aksi bersih pantai, pendistribusian tempat sampah, pemeriksaan kesehatan dasar, dan sosialisasi literasi rupiah untuk memberikan dampak sosial dan lingkungan yang berkelanjutan.",
    "kpi": "Secara Kuantitas:\n- Diikuti oleh 100 anggota GenBI Jatim\n- Pembagian 14 tempat sampah\nSecara Kualitas:\n- Pantai dalam kondisi lebih bersih setelah kegiatan\n- Masyarakat memahami literasi rupiah dan ekonomi dasar",
    "dampak": "-",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "LINGKUNGAN HIDUP DAN SOSIAL",
    "nama_proker": "GenBI Baso",
    "tanggal": "2026-03-15",
    "format": "Offline",
    "status": "Done",
    "deskripsi": "Bakti Sosial (BASO) merupakan program kepedulian sosial yang diselenggarakan oleh GenBI PENS sebagai bentuk kontribusi nyata kepada masyarakat. Kegiatan ini dilaksanakan di Panti Asuhan dan berfokus pada pemberian bantuan kebutuhan pokok, hiburan, serta interaksi positif antara anggota GenBI dan penghuni panti. Melalui kegiatan ini, GenBI berupaya menumbuhkan empati, solidaritas, dan semangat gotong royong demi meningkatkan kesejahteraan bersama.",
    "kpi": "Secara Kuantitas:\n- Penyerahan bantuan berupa alat-alat yang telah disiapkan\n- Diikuti seluruh anggota divisi LHS dan 2 delegasi dari tiap divisi GenBI PENS\nSecara Kualitas:\n- Meningkatnya hubungan sosial dan empati antara GenBI dan penghuni panti\n- Panti asuhan mendapatkan bantuan yang sesuai kebutuhannya\n- Anak-anak panti merasa lebih terhibur dan termotivasi",
    "dampak": "- Menyalurkan bantuan kebutuhan pokok kepada anak-anak panti asuhan guna membantu pemenuhan kebutuhan sehari-hari.\r\n- Memberikan dukungan moral dan kebahagiaan kepada anak-anak panti melalui kegiatan interaksi dan hiburan.\r\n- Menumbuhkan rasa empati, solidaritas, dan kepedulian sosial di kalangan anggota GenBI.\r\n- Mempererat hubungan silaturahmi antara GenBI dan pihak panti asuhan.\r\n- Mewujudkan nilai gotong royong dan pengabdian sosial sebagai bagian dari peran GenBI di masyarakat.",
    "evaluasi": "- Sebagian panitia kurang aktif sehingga progres kegiatan tidak berjalan optimal\r\n- Beberapa anggota hadir tidak tepat waktu\r\n- Beberapa anggota divisi yang terkait tidak hadir dalam pelaksanaan kegiatan",
    "dokumentasi": "GENBI BASO 2026",
    "lpj": "LPJ LHS GENBI PENS 26.pdf",
    "keterangan": ""
  },
  {
    "divisi": "PENDIDIKAN DAN KREATIFITAS",
    "nama_proker": "Konten Edukasi",
    "tanggal": "desember 2025 - januari 2026",
    "format": "Online",
    "status": "Done",
    "deskripsi": "Tiga scope konten untuk program ini berfokus pada tiga topik utama: Bank Indonesia, Genbi (Generasi Baru Indonesia), serta kebijakan dan isu-isu terkait Bank Indonesia. Konten ini akan disajikan dalam bentuk feed atau video reels di Instagram",
    "kpi": "Generasi Muda (Millennials dan Gen Z)\nMahasiswa dan Pelajar\nMasyarakat Umum Penguna instagram\n60 likes  per postingan",
    "dampak": "Meningkatkan literasi masyarakat tentang topik-topik seputar Bank Indonesia, GenBI, dan kebijakan moneter secara sederhana.\n\nMenambah wawasan pengguna instagram melalui penyampaian info edukatif dalam format visual yang mudah dipahami.",
    "evaluasi": "masih bisa lebih rutin lagi untuk pembuatan video",
    "dokumentasi": "Video Edukasi",
    "lpj": "Tidak ada LPJ",
    "keterangan": ""
  },
  {
    "divisi": "PENDIDIKAN DAN KREATIFITAS",
    "nama_proker": "Sosialisasi CBP",
    "tanggal": "-",
    "format": "Offline",
    "status": "Cancel",
    "deskripsi": "Sosialisasi CBP (Cinta, Bangga, dan Paham Rupiah) merupakan kegiatan edukasi yang bertujuan menumbuhkan kesadaran masyarakat tentang pentingnya mengenal, menghargai, dan menggunakan Rupiah sebagai identitas serta alat pemersatu bangsa. Kegiatan ini dilaksanakan berkolaborasi dengan Divisi Ekonomi Kreatif serta dilaksanakan dalam proker Masyarakat Cinta Lingkungan.",
    "kpi": "Memberikan sosialisasi CBP minimal 10 pedagang/masyarakat/pengunjung\nPeserta mampu mempraktikkan kembali materi yang sudah disampaikan",
    "dampak": "Membantu masyarakat memahami pentingnya mengenali, menghargai, dan menggunakan Rupiah sebagai identitas bangsa.\n\nMeningkatkan kesadaran pedagang/pengunjung terkait ciri-ciri keaslian uang Rupiah.\n\nMengurangi potensi peredaran uang palsu melalui edukasi langsung.",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "PENDIDIKAN DAN KREATIFITAS",
    "nama_proker": "Pendidikan Anak Panti",
    "tanggal": "2026-03-15",
    "format": "Offline",
    "status": "Done",
    "deskripsi": "Proker Pendidikan Anak Panti merupakan program edukasi yang berfokus pada peningkatan kemampuan dasar anak-anak panti melalui kegiatan calistung (membaca, menulis, dan menghitung) serta belajar mengaji bagi anak-anak muslim sejalan dengan pelaksanaan yang ada di bulan Ramadhan.",
    "kpi": "Program ini bertujuan meningkatkan kemampuan calistung dan mengaji anak panti, diukur dari partisipasi aktif serta pemahaman dasar yang ditunjukkan selama kegiatan.",
    "dampak": "Membantu mencetak generasi muda yang lebih cerdas dan terdidik, terutama bagi anak-anak yang memiliki keterbatasan akses pendidikan.\n\nMeningkatkan kemampuan dasar anak-anak panti dalam membaca, menulis, dan menghitung.\n\nMeningkatkan motivasi belajar serta rasa percaya diri anak-anak.\n\nMembantu memperluas akses pendidikan yang berkualitas bagi anak panti",
    "evaluasi": "sudah cukup bagus, next nya diharapkan seluruh divisi dari GenBI PEBS untuk ikut",
    "dokumentasi": "GENBI BASO 2026",
    "lpj": "LPJ LHS GENBI PENS 26.pdf",
    "keterangan": ""
  },
  {
    "divisi": "PENGEMBANGAN SUMBER DAYA MANUSIA",
    "nama_proker": "G&g Gather and Grow Monitoring",
    "tanggal": "Desember 2025 - Januari 2026",
    "format": "Online",
    "status": "Done",
    "deskripsi": "Program kerja G&G (Gather and Grow) merupakan salah satu kegiatan utama Divisi Pengembangan Sumber Daya Manusia (PSDM) yang bertujuan untuk memantau serta mendukung pelaksanaan program kerja di setiap divisi GenBI PENS. Melalui kegiatan ini, PSDM berperan sebagai fasilitator dalam menciptakan forum diskusi dan sesi pendampingan (mentoring) yang membahas perkembangan, kendala, serta solusi dari tiap program kerja yang sedang berjalan.",
    "kpi": "TUK: 85% setiap divisi\nWaktu kegiatan: Setiap minggu\nSasaran: GenBI PENS 2025",
    "dampak": "1. Meningkatkan koordinasi antar divisi \n2. Membantu menyelesaikan kendala proker di tiap divisi\n3. Meningkatkan keaktifan dan tanggung jawab anggota\n4. Meningkatkan efektivitas pelaksanaan program kerja",
    "evaluasi": "Menyusul",
    "dokumentasi": "proker PSDM",
    "lpj": "Menyusul",
    "keterangan": ""
  },
  {
    "divisi": "PENGEMBANGAN SUMBER DAYA MANUSIA",
    "nama_proker": "GenBI Sparkfest",
    "tanggal": "-",
    "format": "Hybrid",
    "status": "Cancel",
    "deskripsi": "GenBI Sparkfest adalah salah satu program utama Divisi PSDM yang bertujuan memberikan pemahaman komprehensif kepada anggota GenBI mengenai nilai dasar, sistem keaktifan, kewajiban, hak, serta tanggung jawab sebagai penerima Beasiswa Bank Indonesia. Kegiatan ini menghadirkan pemateri khusus yang memberikan materi sosialisasi dan dilanjutkan dengan forum diskusi interaktif agar anggota memahami peran serta kontribusinya dalam komunitas.",
    "kpi": "TUK: Anggota GenBI PENS 2025 yang hadir minimal 30 orang\nWaktu kegiatan: Desember 2025\nSasaran: GenBI PENS 2025",
    "dampak": "1. Menambah pemahaman anggota tentang GenBI\n2. Meningkatkan motivasi dan sense of belonging\n3. Menumbuhkan kesiapan anggota untuk terlibat aktif\n4. Membangun interaksi yang baik antara anggota dan pengurus",
    "evaluasi": "-",
    "dokumentasi": "-",
    "lpj": "-",
    "keterangan": "SDM genBi PENS banyak yg melaksanakan MAGANG DILUAR KOTA bahkan pulau sehingga sangat tidak memungkinkan untuk pulang ke Surabaya, pula banyak angkatan 2022 yg sedang melaksanakan sidang, evaluasi, dll (Desember 2025 - Mei 2026)"
  },
  {
    "divisi": "PENGEMBANGAN SUMBER DAYA MANUSIA",
    "nama_proker": "Gathering GenBI PENS 2026",
    "tanggal": "akhir bulan mei",
    "format": "Offline",
    "status": "On Progress",
    "deskripsi": "adalah sebuah kegiatan yang mempertemukan awardee genbi pens 2025 dengan awardee genbi pens 2026. kegiatan ini ditujukan agar teman teman dari awardee 2025 and 2026 tidak memiliki jarak yang terlalu jauh, transfer ilmu dan wawasan dari awardee 2025 ke 2026, melakukan bounding awal untuk genbi pens 2026",
    "kpi": "TUK: Anggota GenBI PENS 2025 yang hadir minimal 20 orang, anggota genbi pens 2026 yang hadir minimal 30 orang\nWaktu kegiatan: MEI 2026\nSasaran: GenBI PENS 2025&2026",
    "dampak": "1. Menambah pemahaman anggota tentang GenBI\n2. Meningkatkan motivasi dan sense of belonging\n3. Menumbuhkan kesiapan anggota untuk terlibat aktif\n4. Membangun interaksi yang baik antara anggota dan pengurus",
    "evaluasi": "Menyusul",
    "dokumentasi": "Menyusul",
    "lpj": "Menyusul",
    "keterangan": ""
  }
];
