export const prokerUinsaData = [
  {
    "divisi": "BPH",
    "name": "First Gathering",
    "date": "2025-08-22",
    "format": "Online",
    "status": "DONE",
    "proposal_link": "Proposal First Gathering.pdf",
    "lpj_link": "LPJ First Gathering.pdf",
    "description_short": "kegiatan First Gathering merupakan kegiatan yang melibatkan seluruh anggota GenBI UIN Sunan Ampel Surabaya sehingga dapat saling mengenal, memahami visi-misi organisasi, serta meningkatkan rasa solidaritas untuk bersama-sama berkarya dan berkontribusi bagi masyarakat",
    "description_long": "KPI/TUK/TARGET: Anggota GenBI UINSA 2025/2026\nDAMPAK: Interaksi Internal yang terjalin dengan baik, Meningkatkan Kreatifitas Anggota GenBI\nEVALUASI: Persiapan kondisi data dan wifi yang lebih proper"
  },
  {
    "divisi": "BPH",
    "name": "Rapat Kerja Batch I",
    "date": "2025-09-06",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "Proposal Raker Batch I.pdf",
    "lpj_link": "LPJ Raker Batch I.pdf",
    "description_short": "Melalui kegiatan G-IMPACT, diharapkan seluruh anggota GenBI UIN Sunan Ampel Surabaya dapat memahami serta menerapkan 3 pilar komunitas yakni frontliners, agent of change, dan future leader dalam program kerja selama 1 periode dalam komunitas penerima awardee Bank Indonesia Komisariat UIN Sunan Ampel Surabaya.",
    "description_long": "KPI/TUK/TARGET: Anggota GenBI UINSA 2025/2026\nDAMPAK: anggota GenBI UIN Sunan Ampel Surabaya dapat memahami serta menerapkan 3 pilar komunitas\nEVALUASI: Pemilihan sewa tempat yang lebih affordable untuk mahasiswa"
  },
  {
    "divisi": "BPH",
    "name": "Brand Ambassador GenBI UINSA",
    "date": "2025-09-06",
    "format": "Offline",
    "status": "ON_PROGRESS",
    "proposal_link": "Proposal BA.pdf",
    "lpj_link": "LPJ BA.docx",
    "description_short": "Kegiatan kompetisi tahunan dari komunitas untuk menjadi wajah penyampai kebijakan terkini serta content creator yang menjadi agent of change",
    "description_long": "KPI/TUK/TARGET: Anggota GenBI UINSA terpilih\nDAMPAK: menjadi icon utama dalam menyampaikan kebijakan Bank Indonesia, content creator yang menjadi agent of change yang dapat diterima oleh pengguna media sosial di uar sana.\nEVALUASI: Menyusul"
  },
  {
    "divisi": "BPH",
    "name": "Rapat Kerja Batch II",
    "date": "2025-12-20",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "Proposal Raker Batch II.pdf",
    "lpj_link": "LPJ Raker Batch II.pdf",
    "description_short": "Melalui kegiatan G-IMPACT batch II, diharapkan dapat sebagai kontrol serta evaluasi seluruh anggota GenBI UIN Sunan Ampel Surabaya dalam menerapkan 3 pilar komunitas yakni frontliners, agent of change, dan future leader dalam program kerja selama 1 periode komunitas penerima awardee Bank Indonesia Komisariat UIN Sunan Ampel Surabaya.",
    "description_long": "KPI/TUK/TARGET: Anggota GenBI UINSA 2025-2026\nDAMPAK: anggota GenBI UIN Sunan Ampel Surabaya dapat melihat kekurangan dan kelebihan dalam menerapkan 3 pilar komunitas\nEVALUASI: Menyusul"
  },
  {
    "divisi": "BPH",
    "name": "Sosialisasi Pendaftaran Beasiswa",
    "date": "2026-03-29",
    "format": "Online",
    "status": "ON_PROGRESS",
    "proposal_link": "Proposal Sosialisasi Beasiswa BI.pdf",
    "lpj_link": "LPJ SOSIALISASI BEASISWA BI.pdf",
    "description_short": "Memberikan sosialisasi kepada calon penerima beasiswa Bank Indonesia yang diadakan secara online, Zoom Meeting.",
    "description_long": "KPI/TUK/TARGET: Mahasiswa UINSA\nDAMPAK: Calon penerima beasiswa dapat mengetahui dan memahami flow pendaftaran hingga pemberkasan beasiswa\nEVALUASI: Persiapan yang lebih matang"
  },
  {
    "divisi": "BPH",
    "name": "Farewell Party",
    "date": "contoh: Minggu, 1 Februari 2026",
    "format": "Menyusul",
    "status": "ON_PROGRESS",
    "proposal_link": "Menyusul",
    "lpj_link": "Menyusul",
    "description_short": "Menyusul",
    "description_long": "KPI/TUK/TARGET: Menyusul\nDAMPAK: Menyusul\nEVALUASI: Menyusul"
  },
  {
    "divisi": "MEDINFO",
    "name": "Social Media Specialist (SMS)",
    "date": "2025-09-16",
    "format": "Online",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1y04j6yAwmSu7cmY8UhnZexosVwMHxZJ3/view?usp=sharing",
    "lpj_link": "https://drive.google.com/file/d/1ZwkdIbSFoKLPhvNZKfSwXf0xk9_qrs39/view?usp=sharing",
    "description_short": "Program ini merupakan ujung tombak branding GenBI UINSA yang bertanggung jawab atas pengelolaan terpadu lima platform media sosial: Instagram, TikTok, YouTube, LinkedIn, dan Blog.",
    "description_long": "KPI/TUK/TARGET: Sasaran: Masyarakat Umum. Target: Terlaksananya branding yang kreatif dan aktif di seluruh platform.\nDAMPAK: Meningkatnya citra positif GenBI UINSA, tersampaikannya kebijakan BI ke masyarakat.\nEVALUASI: Kualitas konten agar selalu menarik dan keamanan akun dari risiko kejahatan siber."
  },
  {
    "divisi": "MEDINFO",
    "name": "Connecting Each Other (CEO)",
    "date": "2025-09-16",
    "format": "Online",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1IKU5Z67mnv4WuVbYQ-qiYAKaQS_dQxeb/view?usp=drive_link",
    "lpj_link": "https://drive.google.com/file/d/1kbfQGhaKjAzjIftj2Jcjv84yTZvq2r-W/view?usp=drive_link",
    "description_short": "CEO dirancang sebagai sarana komunikasi strategis antara Divisi Medinfo dengan divisi-divisi lain di internal GenBI UINSA.",
    "description_long": "KPI/TUK/TARGET: Sasaran: Divisi lain internal GenBI UINSA. Target: Terjalinnya komunikasi dan kerjasama yang efektif.\nDAMPAK: Terbentuknya hubungan kerja yang solid antar divisi.\nEVALUASI: Manajemen jadwal editing untuk mencegah bentrok jadwal antar divisi."
  },
  {
    "divisi": "MEDINFO",
    "name": "Company Profile GenBI UINSA",
    "date": "2026-01-04",
    "format": "Online",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1BeCnp3Yi7-tcgc_Z3yd0kSQiZLWGUukD/view?usp=drive_link",
    "lpj_link": "https://drive.google.com/file/d/1LAJa4gBWBjiEM6gxNVaRQL8cfwZVC4gz/view?usp=drive_link",
    "description_short": "Program ini merupakan proyek besar Divisi Medinfo dalam bidang Video Grafis yang berfokus pada produksi Video Company Profile dan Video Mars GenBI.",
    "description_long": "KPI/TUK/TARGET: Sasaran: Pihak Eksternal and Internal. Target: Terilisnya 1 Video Company Profile dan 1 Video Klip Mars GenBI.\nDAMPAK: Memperkuat branding visual organisasi secara signifikan.\nEVALUASI: Risiko ketidakhadiran anggota saat sesi pengambilan video."
  },
  {
    "divisi": "Pendidikan",
    "name": "GeMar: GenBI Mengajar",
    "date": "2025-10-29",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/12pr-cKuQjdyM-t2508xnqV9tpzaOf9I_/view?usp=drivesdk",
    "lpj_link": "LPJ GEMAR 2025.pdf",
    "description_short": "GEMAR (GenBI Mengajar) merupakan salah satu program kerja yang berfokus pada edukasi mengenai CBP (Cinta, Bangga, Paham Rupiah) kepada anak-anak usia dini hingga masyarakat luas.",
    "description_long": "KPI/TUK/TARGET: Memberikan edukasi mengenai CBP kepada anak-anak hingga masyarakat luas.\nDAMPAK: Masyarakat memahami nilai, fungsi, dan simbol kebanggaan Rupiah.\nEVALUASI: Waktu mulai tidak sesuai rundown dan kurangnya sosialisasi H-1."
  },
  {
    "divisi": "Pendidikan",
    "name": "GenMic: GenBI Microsoft",
    "date": "2025-12-03",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "PROPOSAL GEMAR 2025 .pdf",
    "lpj_link": "LPJ GENMIC.pdf",
    "description_short": "Upgrading Skill: Pelatihan Microsoft merupakan program kerja yang dirancang untuk meningkatkan kompetensi anggota GenBI dalam bidang penguasaan teknologi.",
    "description_long": "KPI/TUK/TARGET: Memberikan pemahaman mendalam mengenai keterampilan mengoperasikan Microsoft Excel.\nDAMPAK: Peserta memiliki peningkatan pemahaman mengenai Microsoft Excel.\nEVALUASI: Peserta yang hadir lebih sedikit dari pendaftar dan kendala persiapan tempat."
  },
  {
    "divisi": "Pendidikan",
    "name": "GeShare X GBP (GenBI Sharing Room X GenBI Book Party)",
    "date": "Berkala",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "proposal GESHARE x GBP new.pdf",
    "lpj_link": "LPJ GesharXGBP.docx",
    "description_short": "GESHARE x GenBI BOOK PARTY merupakan program kerja internal berupa kunjungan rutin ke Perpustakaan Bank Indonesia dan forum diskusi buku.",
    "description_long": "KPI/TUK/TARGET: Sarana pengembangan wawasan, literasi, dan ruang berbagi pengetahuan.\nDAMPAK: Memperkuat pemahaman literasi antar anggota GenBI UINSA.\nEVALUASI: Masih ada anggota yang belum mengikuti dan sebagian pertemuan belum terpublikasi."
  },
  {
    "divisi": "PSDM",
    "name": "Fun Sport: Badminton",
    "date": "contoh: Minggu, 1 Februari 2026",
    "format": "Menyusul",
    "status": "DONE",
    "proposal_link": "PROPOSAL FUN SPORT BADMINTON.pdf",
    "lpj_link": "LPJ FUN SPORT BADMINTON.pdf",
    "description_short": "Kegiatan ini diharapkan dapat menjadi wadah untuk meningkatkan kebugaran, melatih semangat sportivitas, dan memperkuat kekompakan anggota GenBI.",
    "description_long": "KPI/TUK/TARGET: Diikuti oleh 4 perwakilan dari setiap divisi dengan total 33 peserta.\nDAMPAK: Menjaga kesehatan fisik dan mempererat silaturahmi antaranggota.\nEVALUASI: Keterlambatan peserta dan keterbatasan jumlah lapangan."
  },
  {
    "divisi": "PSDM",
    "name": "GenMic: GenBI Microsoft",
    "date": "contoh: Minggu, 1 Februari 2026",
    "format": "Menyusul",
    "status": "DONE",
    "proposal_link": "PROPOSAL GENMIC.pdf",
    "lpj_link": "LPJ GENMIC.pdf",
    "description_short": "Upgrading Skill: Pelatihan Microsoft dirancang untuk meningkatkan kompetensi anggota GenBI dan masyarakat umum dalam penguasaan Microsoft Office.",
    "description_long": "KPI/TUK/TARGET: Awardee GenBI UINSA dan mahasiswa umum.\nDAMPAK: Meningkatkan keterampilan praktis peserta dalam mengolah data di Excel.\nEVALUASI: Peserta hadir lebih sedikit dari pendaftar dan kendala persiapan tempat."
  },
  {
    "divisi": "PSDM",
    "name": "G-Connect: GenBI Connect",
    "date": "2025-12-18",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "PROPOSAL STUDI BANDING FIX.pdf",
    "lpj_link": "LPJ G-CONNECT.pdf",
    "description_short": "Program studi banding dengan GenBI UIN Madura untuk saling bertukar pemahaman dan memperluas wawasan organisasi.",
    "description_long": "KPI/TUK/TARGET: Diikuti oleh delegasi GenBI UINSA dan GenBI UIN Madura (60 peserta).\nDAMPAK: Membangun kerja sama dan pertukaran wawasan antar komisariat.\nEVALUASI: Perlu open volunteer dari divisi lain."
  },
  {
    "divisi": "LH",
    "name": "Lomba Infografis \"Creative Action for Green Economy\"",
    "date": "26 Oktober - 09 November 2025",
    "format": "Online",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1UFJHi1PRV4R7i8mUVb3b-Kqh_qSLCfXy/view?usp=drivesdk",
    "lpj_link": "https://drive.google.com/file/d/1E4U-nRJugUlnBeV6AQ-c2QgzxAoOqYE0/view?usp=drivesdk",
    "description_short": "Upaya mendorong kesadaran generasi muda mengenai pentingnya ekonomi hijau melalui karya visual infografis.",
    "description_long": "KPI/TUK/TARGET: Terselenggaranya lomba dengan target ≥150 karya.\nDAMPAK: Meningkatkan awareness ekonomi hijau dan memperkuat peran GenBI sebagai agen perubahan.\nEVALUASI: Kurangnya koordinasi antar panitia meskipun jumlah peserta melebihi target."
  },
  {
    "divisi": "LH",
    "name": "Workshop Hidroponik",
    "date": "2025-12-13",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1xXQCAazVEeURhM_QycdWJnC38kbMhlAa/view?usp=drivesdk",
    "lpj_link": "https://drive.google.com/file/d/1MsglxaAolqMJBvOE9k3CcA64-zWO0MVG/view?usp=drivesdk",
    "description_short": "Mengenalkan cara bercocok tanam ramah lingkungan dengan metode hidroponik kepada anggota GenBI dan mahasiswa umum.",
    "description_long": "KPI/TUK/TARGET: Kehadiran peserta sesuai kuota dan mengikuti seluruh rangkaian materi.\nDAMPAK: Peningkatan pengetahuan dan keterampilan praktik menanam hidroponik.\nEVALUASI: Jumlah peserta yang hadir tidak sesuai pendaftar dan tidak adanya grup koordinasi peserta."
  },
  {
    "divisi": "LH",
    "name": "Rekonstrusi dan Optimalisasi Greenhouse",
    "date": "2026-01-17",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1KxOkAaffTsOJdOHS1jI5shyMhoKs8H5H/view?usp=drivesdk",
    "lpj_link": "https://drive.google.com/file/d/1vYOdl7gd4MQb4ACaq5RLaVWakpbvd5bJ/view?usp=drivesdk",
    "description_short": "Sarana edukasi dan praktik bagi anggota GenBI dalam bidang lingkungan hidup dan pertanian berkelanjutan.",
    "description_long": "KPI/TUK/TARGET: Wadah pembelajaran hidroponik dan pengabdian masyarakat.\nDAMPAK: Meningkatkan keterampilan anggota GenBI dalam pengelolaan tanaman hidroponik.\nEVALUASI: Kegiatan rekonstruksi belum terlaksana karena menunggu konfirmasi proposal."
  },
  {
    "divisi": "LH",
    "name": "Oase EduTrip : Learning and Growing",
    "date": "2026-01-10",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1AfKcQjmFOKz79jGP6vrWBiczSFA5x-aa/view?usp=drivesdk",
    "lpj_link": "https://drive.google.com/file/d/1IREQnD90mtxPq5vpLfC2tMhWyCyaWj_e/view?usp=drivesdk",
    "description_short": "Pembelajaran lapangan fokus pada pengelolaan sampah organik, eco enzyme, dan pertanian terintegrasi di Kampung Oase Songo.",
    "description_long": "KPI/TUK/TARGET: Meningkatkan kesadaran dan keterampilan aplikatif peserta terkait isu lingkungan.\nDAMPAK: Munculnya peran aktif anggota GenBI sebagai penggerak kepedulian lingkungan.\nEVALUASI: Keterlambatan pendaftaran peserta dan keterbatasan area parkir di lokasi."
  },
  {
    "divisi": "KESOSMA",
    "name": "G-Ceria : Genbi Ceria",
    "date": "2025-10-27",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "PROPOSAL - G-CERIA.pdf",
    "lpj_link": "LPJ G-CERIA 2025.pdf",
    "description_short": "Memberikan pengalaman belajar yang menyenangkan bagi anak-anak berkebutuhan khusus di SLB Negeri Gedangan.",
    "description_long": "KPI/TUK/TARGET: Terlaksananya kegiatan dengan minimal 25 siswa SLB.\nDAMPAK: Meningkatkan empati anggota GenBI terhadap anak berkebutuhan khusus.\nEVALUASI: Beberapa permainan memerlukan adaptasi kondisi peserta namun tetap berjalan lancar."
  },
  {
    "divisi": "KESOSMA",
    "name": "Genor : Genbi Donor Darah",
    "date": "2025-11-03",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "PROPOSAL_GENOR_2025.pdf",
    "lpj_link": "LPJ_GENOR_2025.pdf",
    "description_short": "Kegiatan kemanusiaan kolaborasi dengan PMI untuk membantu memenuhi kebutuhan darah dan meningkatkan kesadaran sosial.",
    "description_long": "KPI/TUK/TARGET: Target minimal 75 peserta aktif dan 50 kantong darah.\nDAMPAK: Membantu stok darah PMI dan membentuk budaya solidaritas mahasiswa.\nEVALUASI: Jumlah kantong darah tidak mencapai target karena banyak peserta tidak lolos screening kesehatan."
  },
  {
    "divisi": "PAREKRAF",
    "name": "Genbi LPSperience : Goes to LPS II Surabaya",
    "date": "2025-11-05",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1aqpaUKq-t5j-jEixp7HKUdbDcrmxPXr0/view?usp=sharing",
    "lpj_link": "https://drive.google.com/file/d/1Koe-JQBgchlh7E-NeSFA3GXwQuelZwf_/view?usp=sharing",
    "description_short": "Kunjungan edukatif untuk meningkatkan literasi keuangan mengenai peran Lembaga Penjamin Simpanan (LPS).",
    "description_long": "KPI/TUK/TARGET: Kehadiran 50-60 anggota dan adanya sharing session dengan awardee LPS.\nDAMPAK: Membangun relasi kelembagaan dan memberikan exposure dunia kerja sektor keuangan.\nEVALUASI: Perlu penambahan waktu sesi sharing agar peserta lebih memahami praktik kerja LPS."
  },
  {
    "divisi": "PAREKRAF",
    "name": "GenBI IDXplore : Goes to PT Bursa Efek Indonesia",
    "date": "2025-11-27",
    "format": "Offline",
    "status": "DONE",
    "proposal_link": "https://drive.google.com/file/d/1TWBLGXyCtfc-4ftua8UmSTyim9juyFIu/view?usp=sharing",
    "lpj_link": "https://drive.google.com/file/d/1K_P5Bx3uW5hgDcgrBqTMUS6B13mzqtv3/view?usp=sharing",
    "description_short": "Kunjungan edukasi pasar modal untuk meningkatkan pemahaman mengenai investasi dan peran Bursa Efek Indonesia (IDX).",
    "description_long": "KPI/TUK/TARGET: Kehadiran 50-60 peserta dan adanya sesi simulasi investasi.\nDAMPAK: Mendorong literasi investasi yang sehat dan terukur bagi generasi muda.\nEVALUASI: Masukan peserta menunjukkan perlunya tambahan sesi praktik atau studi kasus."
  }
];
