export const prokerUnairData = [
  {
    "Divisi": "PSDM",
    "Nama Proker": "Welcome Party & Upgrading",
    "Tanggal Proker": "2025-10-11",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "PROPOSAL WELGRADING GENBI UNAIR 2025.docx 2.pdf",
    "Deskripsi Proker": "Merupakan sebuah acara yang diselenggarakan sebagai tempat awardee untuk saling mengenal satu sama lain dan menyatukan visi kedepan.",
    "KPI/Target": "1. Kehadiran 50% pengurus GenBI UNAIR \n2. Acara dapat berjalan tepat Waktu dan sesuai dengan anggaran dana",
    "Dampak": "Menciptakan komunikasi yang efektif, meningatkan bonding pengurus, dan menentukan visi dan misi.",
    "Evaluasi": "1. Penyusunan acara sebaiknya dilakukan lebih awal agar terdapat Waktu yang cukup untuk melakukan revisi atau penyesuaian jika diperlukan\n2. Disarankan agar komunikasi dalam divisi dilakukan melalui satu jalur atau satu pintu agar informasi yang disampaikan lebih jelas, terarah, dan dapat meminimalisir miskomunikasi",
    "Dokumentasi": "ACARA",
    "Link LPJ": "LPJ WELPAR 2025.docx.pdf"
  },
  {
    "Divisi": "PSDM",
    "Nama Proker": "Webinar",
    "Tanggal Proker": "Menyusul",
    "Format Pelaksanaan": "Online",
    "Status": "nan",
    "Link Proposal": "Menyusul",
    "Deskripsi Proker": "Merupakan kegiatan webinar yang membahas mengenai bagaimana AI dapat membantu persiapan karier di masa depan.",
    "KPI/Target": "Mengukur peningkatan pemahaman peserta mengenai pemanfaatan AI iuntuk persiapan karir melalui partisipasi aktif peserta selama webinar.",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "PSDM",
    "Nama Proker": "Eternal Party (farewall party)",
    "Tanggal Proker": "Menyusul",
    "Format Pelaksanaan": "Offline",
    "Status": "On Progress",
    "Link Proposal": "Menyusul",
    "Deskripsi Proker": "Acara Perpipsahan yang diadakan sebagai bentuk apresiasi kepada para awardee selama satu priode kepengurusan",
    "KPI/Target": "1. Kehadiran 50% pengurus GenBI UNAIR \n2. Acara dapat berjalan tepat Waktu dan sesuai dengan anggaran dana",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "EKRAF",
    "Nama Proker": "GenBI Identity",
    "Tanggal Proker": "5 Oktober - 8 November 2025",
    "Format Pelaksanaan": "Hybrid",
    "Status": "Done",
    "Link Proposal": "Proposal GenBI Identity 2025 (ACC).pdf",
    "Deskripsi Proker": "Program kerja GenBI Identity merupakan kegiatan pengadaan lanyard dan ID card yang akan digunakan oleh seluruh 112 awardee GenBI UNAIR. Penyediaan identitas fisik ini tidak hanya berfungsi sebagai pengenal, tetapi juga sebagai bentuk penghargaan dan pengakuan atas prestasi yang telah dicapai oleh para awardee. Program GenBI Identity ini diharapkan dapat memperkuat ikatan di antara para awardee serta meningkatkan sense of belonging terhadap komunitas GenBI UNAIR. Selain itu, identitas yang seragam ini juga akan memudahkan koordinasi dan pelaksanaan berbagai kegiatan GenBI di lingkungan kampus maupun masyarakat.",
    "KPI/Target": "1. ID Card terdistribusikan dengan lengkap kepada seluruh awardee GenBI UNAIR (112 orang)\n2. Anggaran terserap sesuai rencana dan target\n3. Timeline pelaksanaan program berjalan sesuai rencana",
    "Dampak": "1. Menciptakan rasa kebersamaan dan identitas yang seragam di antara para awardee GenBI yang dapat meningkatkan semangat kerja tim\n2. Menyertakan informasi mengenai status sebagai awardee GenBI",
    "Evaluasi": "1. Koordinasi kurang optimal sehingga beberapa informasi terlambat diterima\n2. Beberapa peserta terlambat mengisi formulir pendataan",
    "Dokumentasi": "GENBI IDENTITY ID CARD",
    "Link LPJ": "LPJ GenBI Identity 2025_ACC.pdf"
  },
  {
    "Divisi": "EKRAF",
    "Nama Proker": "GenBiz",
    "Tanggal Proker": "2025-11-08",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal GenBiz 2025_ACC.pdf",
    "Deskripsi Proker": "Program kerja GenBiz 2025 merupakan rangkaian talkshow yang akan dilaksanakan dalam bentuk diskusi interaktif dengan menghadirkan narasumber dari perwakilan Bank Indonesia. Peserta yang mengikuti adalah mahasiswa dan pelaku UMKM yang telah mendaftar melalui formulir online. Format acara mencakup pemaparan materi dan sesi tanya jawab.",
    "KPI/Target": "1. Dihadiri oleh minimal 50 peserta talkshow\n2. Anggaran terserap sesuai rencana dan target",
    "Dampak": "1. Membekali pelaku UMKM, terutama dari kalangan mahasiswa GenBI, dengan pengetahuan dan jejaring yang diperlukan\n2. Memberikan edukasi manajemen usaha dan investasi melalui talkshow interaktif bersama narasumber",
    "Evaluasi": "1. Proses koordinasi lebih lambat karena melibatkan kolaborasi dengan pihak luar GenBI\n2. Pembagian tupoksi yang telah dibagi belum sepenuhnya dilaksanakan dengan baik karena minimnya waktu persiapan kegiatan",
    "Dokumentasi": "DOKUMENTASI GENBIZ",
    "Link LPJ": "LPJ GenBiz 2025_ACC.pdf"
  },
  {
    "Divisi": "EKRAF",
    "Nama Proker": "UMKM Ignite",
    "Tanggal Proker": "2026-02-05",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal UMKM Ignite 2025_ACC.pdf",
    "Deskripsi Proker": "Dalam acara ini terdapat rangkaian acara sosialisasi terkait pemberdayaan UMKM melalui program QRIS dan SIAPIK dengan menghadirkan narasumber dari Bank Indonesia. Selain itu, terdapat sosialisasi terkait pemanfaatan e-commerce sebagai bagian dari strategi pengembangan usaha yang berkelanjutan serta melakukan pendampingan langsung kepada pelaku UMKM di kelurahan Tambak Wedi. Format acara mencakup pemaparan materi, sesi tanya jawab, dan pendampingan praktik pendaftaran e-commerce, sehingga peserta memperoleh pemahaman lebih mendalam mengenai strategi pengembangan UMKM.",
    "KPI/Target": "1. Diikuti oleh minimal 5 UMKM pendaftar\n2. Anggaran terserap sesuai rencana dan target\n3. Berjalan sesuai timeline yang sudah direncanakan",
    "Dampak": "1. Meningkatkan pemahaman UMKM terkait program BI yaitu QRIS dan SIAPIK\n2. Meningkatkan daya saing produk UMKM daerah melalui pemahaman terkait E-Commerce dengan praktik langsung",
    "Evaluasi": "Proses koordinasi lebih lambat karena melibatkan kolaborasi dengan banyak pihak di luar divisi",
    "Dokumentasi": "DOKUMENTASI UMKM IGNITE",
    "Link LPJ": "LPJ UMKM IGNITE 2026_ACC.pdf"
  },
  {
    "Divisi": "PENGMAS",
    "Nama Proker": "GenBI Blood for Hope",
    "Tanggal Proker": "2025-11-18",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "https://drive.google.com/file/d/1sql8Ly4jBUTSrpV7rSgELgyiZzjWGI3K/view?usp=sharing",
    "Deskripsi Proker": "Kegiatan donor darah merupakan aksi sosial-kemanusiaan yang dilakukan secara sukarela oleh individu untuk menyumbangkan darahnya melalui prosedur medis yang aman, bekerja sama dengan Palang Merah Indonesia (PMI) sebagai lembaga resmi penyedia layanan transfusi darah di Indonesia.",
    "KPI/Target": "Donasi 75 Kantong Darah",
    "Dampak": "1. Meningkatkan ketersediaan stok darah\n2. Menumbuhkan kepedulian sosial\n3. Memperkuat citra organisasi sebagai pihak yang peduli kemanusiaan.",
    "Evaluasi": "1. Persingkat jam pelaksanaan karena kantung darah maksimal 4 jam\n2. Perbanyak peserta yang daftar agar mengantisipasi gagal donor",
    "Dokumentasi": "https://drive.google.com/drive/folders/1GPbETio-K0KPh6vb6OjG0Us4_jA02AtQ?usp=sharing",
    "Link LPJ": "https://drive.google.com/file/d/1wMQV3V7YMFA9IkL4pI8SzL-8-oZzDDbJ/view?usp=sharing"
  },
  {
    "Divisi": "PENGMAS",
    "Nama Proker": "Abdi Desa 2025",
    "Tanggal Proker": "Rabu-Kamis, 4-5 Februari 2026",
    "Format Pelaksanaan": "Offline",
    "Status": "On Progress",
    "Link Proposal": "https://drive.google.com/file/d/1fgOc06c00ypcaLNdGlV6GC8-Hj9APm0C/view?usp=sharing",
    "Deskripsi Proker": "Bina Abdi Desa merupakan program pengembangan dan pembinaan bagi mahasiswa sebagai bentuk persiapan sebelum terjun ke masyarakat. Program ini berfokus pada peningkatan kapasitas, penanaman nilai pengabdian, serta pembekalan keterampilan manajerial, komunikasi, dan inovasi.",
    "KPI/Target": "Berhasil diadakannya program kerja unggulan dan non unggulan dengan baik untuk menghasilkan desa kontrak yang terdigitalisasi",
    "Dampak": "Menjadi wadah untuk pemberdayaan UMKM bagi masyarakat di Kelurahan Tambak Wedi, Surabaya melalui dilaksanakannya program unggulan dan non-unggulan.",
    "Evaluasi": "Menyusul",
    "Dokumentasi": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "PENDIDIKAN",
    "Nama Proker": "GenBI Goes to School",
    "Tanggal Proker": "2025-12-12",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "PROPOSAL GGTS GENBI UNAIR 2025 (2) (1).pdf",
    "Deskripsi Proker": "GenBI Goes to School merupakan program kerja dari Departemen Pendidikan dengan konsep edukasi dan sosialisasi tentang Beasiswa Bank Indonesia serta Generasi Baru Indonesia (GenBI) ke salah satu SMA di Surabaya.",
    "KPI/Target": "1. Acara berjalan lancar\n2. Peserta melebihi target (120 siswa)\n3. Peserta memahami materi melalui pre/post test",
    "Dampak": "Meningkatkan wawasan mengenai Beasiswa BI dan peran GenBI bagi siswa SMA, menumbuhkan motivasi pendidikan tinggi, dan memperkuat citra positif organisasi.",
    "Evaluasi": "Kurang maksimalnya komunikasi antar panitia dan ketidakcocokan waktu dengan pihak sekolah yang menyebabkan kemunduran timeline.",
    "Dokumentasi": "GGTS",
    "Link LPJ": "LPJ GGTS GENBI UNAIR 2025 (2).pdf"
  },
  {
    "Divisi": "PENDIDIKAN",
    "Nama Proker": "EduAction",
    "Tanggal Proker": "2026-02-04",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "PROPOSAL EDUACTION GENBI UNAIR 2026_Terbaru (3).pdf",
    "Deskripsi Proker": "EduAction adalah program kerja yang berfokus pada pemberian edukasi mengenai Cinta, Bangga, dan Paham Rupiah (CBP) kepada anak-anak tingkat Sekolah Dasar (SD).",
    "KPI/Target": "1. Acara berjalan lancar\n2. Peserta 45 siswa SD\n3. Peserta mampu menjawab kuis dan demonstrasi 5J",
    "Dampak": "Meningkatkan literasi keuangan dasar dan penanaman nilai kebangsaan sejak dini pada siswa SD melalui pengenalan Rupiah.",
    "Evaluasi": "Kurang maksimalnya komunikasi dan ketidakpastian kehadiran panitia sehingga terkendala dalam pembagian jobdesc.",
    "Dokumentasi": "EDUACTION",
    "Link LPJ": "LPJ EDUACTION GENBI 2026"
  },
  {
    "Divisi": "PENDIDIKAN",
    "Nama Proker": "Genbipedia",
    "Tanggal Proker": "tidak ada",
    "Format Pelaksanaan": "Online",
    "Status": "Done",
    "Link Proposal": "tidak ada proposal",
    "Deskripsi Proker": "Konsep penyebarluasan ilmu pengetahuan terkait kelembagaan dan kebijakan Bank Indonesia dalam bentuk infografis.",
    "KPI/Target": "Konsisten upload konten (minimal 1-2 kali sebulan). Engagement rate 3-5%",
    "Dampak": "Meningkatkan literasi publik terhadap peran Bank Indonesia.",
    "Evaluasi": "nan",
    "Dokumentasi": "GENBIPEDIA",
    "Link LPJ": "tidak ada LPJ"
  },
  {
    "Divisi": "HUBLU",
    "Nama Proker": "GenBI Company Visit",
    "Tanggal Proker": "2025-11-28",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal GenBI Company Visit 2025",
    "Deskripsi Proker": "Program edukasi kunjungan langsung ke Bursa Efek Indonesia (IDX) Jawa Timur untuk meningkatkan literasi pasar modal bagi anggota.",
    "KPI/Target": "1. Acara lancar\n2. Kehadiran minimal 75%\n3. Pemahaman materi infrastruktur pasar modal",
    "Dampak": "Memperluas pemahaman mekanisme kerja IDX, wawasan karier, dan mempererat hubungan GenBI dengan lembaga strategis.",
    "Evaluasi": "Kegiatan berjalan baik, namun perlu perbaikan pada ketepatan waktu dan koordinasi teknis di masa mendatang.",
    "Dokumentasi": "DOKUMENTASI COMPANY VISIT",
    "Link LPJ": "LPJ GenBI COMPANY VISIT"
  },
  {
    "Divisi": "HUBLU",
    "Nama Proker": "GenBI Visit",
    "Tanggal Proker": "2025-11-29",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal GenBI Visit 2025",
    "Deskripsi Proker": "Kunjungan antar-komisariat ke GenBI Malang untuk memperkuat jejaring, kolaborasi, dan pertukaran wawasan program unggulan.",
    "KPI/Target": "1. Terlaksananya rangkaian acara (FGD, presentasi, dll)\n2. Keterlibatan aktif anggota dalam diskusi\n3. Pertukaran materi profil dan program kerja",
    "Dampak": "Memperkuat hubungan antarkomisariat, meningkatkan wawasan organisasi, dan membuka peluang kolaborasi masa depan.",
    "Evaluasi": "Acara berjalan lancar, peserta antusias, namun terdapat catatan teknis kecil untuk perbaikan koordinasi panitia.",
    "Dokumentasi": "DOKUMENTASI GENBI VISIT 2025",
    "Link LPJ": "LPJ GenBI VISIT"
  },
  {
    "Divisi": "MEDKOM",
    "Nama Proker": "GenBI Company Profile",
    "Tanggal Proker": "11 Okt 2025 - 5 Nov 2025",
    "Format Pelaksanaan": "Hybrid",
    "Status": "Done",
    "Link Proposal": "PROPOSAL GENBI COMPROF 2025.pdf",
    "Deskripsi Proker": "Kegiatan pembuatan foto profil representatif anggota untuk membangun citra profesional dan transparansi di media sosial.",
    "KPI/Target": "Seluruh foto anggota terunggah di Instagram GenBI UNAIR",
    "Dampak": "Meningkatkan pengenalan anggota ke publik and engagement media sosial.",
    "Evaluasi": "Terlaksana lancar, namun ada keterlambatan pengumpulan foto dari beberapa anggota.",
    "Dokumentasi": "Link Drive",
    "Link LPJ": "LPJ GENBI COMPROF 2025.pdf"
  },
  {
    "Divisi": "MEDKOM",
    "Nama Proker": "KOMEDIA",
    "Tanggal Proker": "Selama masa kepengurusan",
    "Format Pelaksanaan": "Online",
    "Status": "Done",
    "Link Proposal": "(Tidak ada proposal)",
    "Deskripsi Proker": "Layanan kreatif internal untuk produksi media (desain, video, dokumentasi) guna publikasi kegiatan seluruh divisi.",
    "KPI/Target": "Seluruh permohonan pembuatan konten terlaksana",
    "Dampak": "Meningkatkan kinerja publikasi konten setiap program kerja.",
    "Evaluasi": "Permohonan terlaksana dengan baik, meski beberapa memerlukan penyesuaian optimalisasi.",
    "Dokumentasi": "-",
    "Link LPJ": "(Tidak ada LPJ)"
  },
  {
    "Divisi": "MEDKOM",
    "Nama Proker": "GenBI Info",
    "Tanggal Proker": "Selama masa kepengurusan",
    "Format Pelaksanaan": "Online",
    "Status": "Done",
    "Link Proposal": "(Tidak ada proposal)",
    "Deskripsi Proker": "Penyediaan konten informatif seputar kebijakan Bank Indonesia, ekonomi, dan event GenBI untuk masyarakat.",
    "KPI/Target": "Minimal 4 konten edukatif per periode",
    "Dampak": "Meningkatkan pengetahuan publik dan internal mengenai Bank Indonesia.",
    "Evaluasi": "1.",
    "Dokumentasi": "-",
    "Link LPJ": "(Tidak ada LPJ)"
  }
];
