export const prokerUpnvjtData = [
  {
    "nama_proker": "Welcoming Party dan Rapat Kerja",
    "divisi": "Divisi BPH",
    "status": "DONE",
    "tanggal": "2025-09-21",
    "deskripsi": "Welcoming Party dan Rapat Kerja GenBI UPNVJT bertujuan mengenalkan anggota, membangun keakraban antardivisi, memaparkan proker satu periode, mengenalkan GenBI dan strukturnya, serta berbagi pengalaman dan peluang kegiatan bagi anggota.",
    "description_long": "KPI:\n1. Anggota baru saling mengenal dan memahami peran masing-masing.\n2. Terbentuk bonding kuat antardivisi.\n3. Seluruh anggota memahami struktur GenBI UPNVJT.\n4. Peserta mengetahui program kerja yang akan dijalankan.\n5. Anggota mendapat insight dari pengalaman kakak existing.\n6. Anggota mengetahui lomba/kegiatan yang dapat diikuti sebagai GenBI.\n\nDampak:\n1. Meningkatnya kekompakan internal GenBI UPNVJT.\n2. Anggota lebih memahami arah gerak dan budaya komunitas.\n3. Terbentuk motivasi dan semangat berkontribusi dalam satu periode kepengurusan.\n\nEvaluasi:\n1. Terjadi kemunduran rundown sekitar 30–40 menit dari jadwal yang direncanakan.\n2. Keterlambatan memengaruhi efektivitas penyampaian materi dan sesi bonding.",
    "link_proposal": "Tidak ada proposal",
    "link_lpj": "Tidak ada LPJ",
    "link_dokumentasi": "PROKER 1_Welcoming Party dan Rapat Kerja"
  },
  {
    "nama_proker": "Boothcamp Medkom",
    "divisi": "Divisi BPH",
    "status": "DONE",
    "tanggal": "2025-11-14",
    "deskripsi": "Bootcamp Divisi Medkom bertujuan membekali anggota dengan basic Figma, Canva, copywriting, penyusunan skrip, pencarian ide, serta pembuatan hook konten melalui materi dari para pemateri internal Medkom.",
    "description_long": "KPI:\n1. Anggota memahami dasar penggunaan Figma dan Canva.\n2. Meningkatkan kemampuan copywriting dan penyusunan skrip konten.\n3. Anggota mampu merancang ide dan hook konten yang menarik.\n4. Menyamakan standar kerja divisi Medkom satu periode.\n5. Meningkatkan kualitas output konten GenBI UPNVJT.\n\nDampak:\n1. Skill desain dan penulisan konten anggota meningkat.\n2. Proses produksi konten menjadi lebih cepat dan terstruktur.\n3. Output konten Medkom lebih konsisten dan menarik.\n4. Anggota lebih percaya diri mengerjakan proyek konten.\n\nEvaluasi:\n1. Perlu latihan praktik lebih banyak agar skill lebih terasah.\n2. Perlu modul atau dokumentasi materi sebagai referensi lanjutan.\n3. Waktu tanya jawab perlu ditambah.\n4. Secara keseluruhan peserta antusias dan pemateri komunikatif.",
    "link_proposal": "Tidak ada proposal",
    "link_lpj": "Tidak ada LPJ",
    "link_dokumentasi": "PROKER 3_Boothcamp Medkom"
  },
  {
    "nama_proker": "GenBI Skill-Up Reel Competition",
    "divisi": "Divisi BPH",
    "status": "DONE",
    "tanggal": "2025-11-26",
    "deskripsi": "Kompetisi Reel untuk awardee GenBI UPNVJT yang mengikuti BNSP sebagai wadah berbagi pengalaman, insight, skill yang didapat, dan momen pengembangan diri melalui konten kreatif berdurasi maksimal 60 detik di Instagram.",
    "description_long": "KPI:\n1. Awardee mampu menceritakan pengalaman dan pembelajaran selama BNSP.\n2. Mendorong kreativitas anggota melalui pembuatan konten.\n3. Meningkatkan exposure GenBI UPNVJT di media sosial.\n4. Mendokumentasikan proses pengembangan skill anggota.\n5. Menumbuhkan budaya berbagi insight antarawardee.\n\nDampak:\n1. Meningkatnya kemampuan konten kreatif awardee.\n2. Terbangunnya kebiasaan refleksi setelah mengikuti pelatihan BNSP.\n3. Terbentuknya portofolio digital yang bermanfaat bagi peserta.\n\nEvaluasi:\n1. Sebagian peserta terlambat mengumpulkan link Reel sehingga penilaian mundur.\n2. Beberapa akun masih private sehingga perlu verifikasi ulang.\n3. Perlu reminder lebih awal untuk mencegah keterlambatan upload.",
    "link_proposal": "Tidak ada proposal",
    "link_lpj": "Tidak ada LPJ",
    "link_dokumentasi": "PROKER 2_GenBI Skill-Up Reel Competition"
  },
  {
    "nama_proker": "FunPost",
    "divisi": "Divisi Media dan Komunikasi",
    "status": "DONE",
    "tanggal": "Post setiap 1 minggu sekali",
    "deskripsi": "Konten mingguan yang berfungsi untuk menjaga engagement sosial media",
    "description_long": "KPI:\n6 Content per Month (4 feeds & 2 reels)\n\nDampak:\nKeterlibatan publik seperti orang yang menyukai postingan, memberikan komentar, dan membagian postingan menjadi meningkat selama periode.\n\nEvaluasi:\n- Pas awal sudah dibagi jobdesknya masing-masing, akan tetapi kurang efisien, jadi bulan desember awal diganti ke metode end to end . - Perlu dicroshcheek lagi terkait penulisan angka rupiah.",
    "link_proposal": "karena ini agenda medkom, bukan proker",
    "link_lpj": "https://docs.google.com/document/d/1aY5PMEY0JArwrVaHuBT2lyWZpnYBhO1j/edit?usp=sharing",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1y0cahwHeelQlz10wnjPYSXgmcrZJG24S"
  },
  {
    "nama_proker": "Website Company Profile",
    "divisi": "Divisi Media dan Komunikasi",
    "status": "DONE",
    "tanggal": "November 2025 - Januari 2026",
    "deskripsi": "Pembangunan website Company Profile resmi untuk GenBI UPNVJT",
    "description_long": "KPI:\nNovember 2025 - Januari 2026\n\nDampak:\nPeningkatan kredibilitas company di mata audiens.\n\nEvaluasi:\nTidak Ada Evaluasi, Update Data Pembimbing",
    "link_proposal": "Tidak ada",
    "link_lpj": "https://docs.google.com/document/d/1j-sZ8ZwXSOb0nPDyGqYUyvy4yE-6H8hK/edit?usp=sharing",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1yhTcrY1WX3v38HnAIUrCP7_MvWwybVcK"
  },
  {
    "nama_proker": "Pembuatan PDH",
    "divisi": "Divisi Media dan Komunikasi",
    "status": "DONE",
    "tanggal": "1 September - 30 September 2025",
    "deskripsi": "Membuat Baju Kerja untuk GenBI Komisariat UPNVJT",
    "description_long": "KPI:\n1 - 30 September 2025\n\nDampak:\nTerlihat rapi dalam hal berpakaian ketika melakukan suatu kegiatan program kerja\n\nEvaluasi:\nTidak Ada Evaluasi",
    "link_proposal": "Tidak Ada",
    "link_lpj": "Tidak Ada LPJ",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1-JNm0eGwIjsyAyFDZsQ2NXPKNaGx8aHI"
  },
  {
    "nama_proker": "GenZine",
    "divisi": "Divisi Media dan Komunikasi",
    "status": "DONE",
    "tanggal": "Post setiap 1 minggu sekali",
    "deskripsi": "Ragkuman tiap akhir bulan tentang apa saja yang sudah kita capai dan kegiatan apa saja yang sudah kita jalankan",
    "description_long": "KPI:\n6 content/Period , 1 content/Month\n\nDampak:\nMeningkatnya visibilitas dan reach konten GenZine karena konten yang konsisten, peningkatan engagement dari audiens, dan lebih banyak yang share.\n\nEvaluasi:\nTidak Ada Evaluasi",
    "link_proposal": "karena ini agenda medkom, bukan proker",
    "link_lpj": "Tidak Ada LPJ",
    "link_dokumentasi": "https://drive.google.com/drive/folders/10bFBOV7mGaPRPdOS7K4iqU_XzjYJrheu"
  },
  {
    "nama_proker": "GenBiver",
    "divisi": "Divisi Media dan Komunikasi",
    "status": "DONE",
    "tanggal": "Setiap 1 Minggu Sekali di tiap Bulan",
    "deskripsi": "Sebagai wadah sharing pengalaman/aktivitas diluar GenBI yang relateable dengan kehidupan mahasiswa.",
    "description_long": "KPI:\n4 content/period , 1 content/Month\n\nDampak:\nMeningkatnya pengetahuan mengenai kehidupan mahasiswa diluar GenBI\n\nEvaluasi:\nTidak Ada Evaluasi",
    "link_proposal": "karena ini agenda medkom, bukan proker",
    "link_lpj": "https://docs.google.com/document/d/1vXpdFXcsJMH5Ex6HfXBxJIEYLuWQ4dnH/edit?usp=sharing",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1Aq3e_Q8xMdd2RklsNGu7wf6k0t7KUa9_"
  },
  {
    "nama_proker": "English Proficiency Test Preparation",
    "divisi": "Divisi PSDM",
    "status": "DONE",
    "tanggal": "2025-11-30",
    "deskripsi": "English ProficiencyTest Preparation merupakan kegiatan seminar offline yang diadakan untuk memberikan pemahaman serta tips and trick dalam mengerjakan tes kemampuan bahasa Inggris, yaitu EPT, kepada anggota GenBI UPN \"Veteran\" Jawa Timur.",
    "description_long": "KPI:\nTarget peserta adalah 75% dari 42 anggota GenBI UPNVJT (kecuali panitia)\n\nDampak:\n1. Peserta mendapatkan pemahaman yang lebih baik terkait EPT.\n2. Peserta mendapatkan teknik dan strategi efektif.\n3. Peserta menjadi lebih percaya diri.\n\nEvaluasi:\n1. Pergantian ruangan tiba-tiba.\n2. Proyektor tidak berfungsi.\n3. Kekurangan panitia.\n4. Anggaran melebihi rancangan.",
    "link_proposal": "https://drive.google.com/file/d/1idfjFEhmVBCJt4VwHTm3Kf-15acKzbab/view",
    "link_lpj": "https://drive.google.com/file/d/1kdK2Dwp_F3KzPLtFupI5dpkynkueDwIj/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1b0-9YEtAq6bC7SFtjmTLql4uZrXS87w6"
  },
  {
    "nama_proker": "GenBI Farewell Party",
    "divisi": "Divisi PSDM",
    "status": "DONE",
    "tanggal": "Sabtu, 9 Mei 2026",
    "deskripsi": "Kegiatan apresiasi dan perpisahan bagi anggota GenBI Komisariat UPN “Veteran” Jawa Timur sebagai bentuk penghargaan atas kontribusi selama masa kepengurusan.",
    "description_long": "KPI:\nSeluruh anggota GenBI UPN \"Veteran\" Jawa Timur periode 2025\n\nDampak:\n1. Meningkatnya rasa apresiasi.\n2. Terjalinnya hubungan erat.\n3. Terciptanya kenangan positif.\n\nEvaluasi:\ntidak ada",
    "link_proposal": "https://drive.google.com/file/d/1y72WU2dnbTpjK1Zk6wVYjAzAXm6mfNM7/view",
    "link_lpj": "tidak ada LPJ",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1PoPd2kBN9AlNiDUJGR4gyWQ7BYVc6-Ws"
  },
  {
    "nama_proker": "Pelita: Pelatihan Seni Merangkai Bunga Tangan",
    "divisi": "Divisi PSDM",
    "status": "DONE",
    "tanggal": "2026-02-14",
    "deskripsi": "Kegiatan ini bertujuan untuk meningkatan kreatifitas dan keterampilan anggota GenBI melalui pembuatan buket bunga menggunakan bahan kawat bulu.",
    "description_long": "KPI:\nAnggota GenBI UPN \"Veteran\" Jawa Timur\n\nDampak:\n1. Mahasiswa memperoleh keterampilan baru.\n2. Meningkatkan kepercayaan diri dan peluang kewirausahaan.\n\nEvaluasi:\n1. Persiapan photo booth memakan waktu lama.\n2. Jadwal pembukaan mundur.\n3. Peserta tidak tepat waktu.",
    "link_proposal": "https://drive.google.com/file/d/1gilmceivXCWYr19m4Uufkiu1XS2FhU8W/view",
    "link_lpj": "https://drive.google.com/file/d/10N-aWc2WVxQ-6rn2pZup1E2avWoiJxlK/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1jsUiO-lUP8QqXls9qFmJBaVibc2UXT6H"
  },
  {
    "nama_proker": "Genbi Shine: Sharing Health, Inspiring New Education",
    "divisi": "Divisi Sosial dan Lingkungan",
    "status": "DONE",
    "tanggal": "Minggu, 26 Oktober 2025 dan Sabtu, 29 November 2025",
    "deskripsi": "Program kolaboratif antara Divisi Pendidikan dan Divisi Sosial Lingkungan untuk meningkatkan literasi keuangan sekaligus kesadaran kesehatan anak.",
    "description_long": "KPI:\n1. Target 30 peserta (26 Okt)\n2. Target 50 peserta (29 Nov)\n\nDampak:\n1. Pemahaman pengelolaan uang dan PHBS.\n2. Kebiasaan disiplin dan sehat.\n3. Kontribusi nyata GenBI.\n\nEvaluasi:\n1. Data peserta berubah hari H.\n2. Penyambutan kurang optimal.\n3. Peserta sering keluar masuk.",
    "link_proposal": "https://drive.google.com/file/d/18llxb9gzo3cJ6TpIjg8zN8vroPPARSzR/view",
    "link_lpj": "https://drive.google.com/file/d/1q2JPLtgET5iNhCGlOSYhWtdMR4QNHFhw/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1FiDFWLVLYKl8-TcVFg6rgISZ1XAy4f9B"
  },
  {
    "nama_proker": "Genbi Little Planters",
    "divisi": "Divisi Sosial dan Lingkungan",
    "status": "DONE",
    "tanggal": "2025-12-04",
    "deskripsi": "Kegiatan edukatif mengenalkan proses menanam dan merawat tanaman untuk menumbuhkan rasa tanggung jawab terhadap alam sejak dini.",
    "description_long": "KPI:\n1. Target 30 orang hadir\n2. Peserta berperan aktif di lapangan\n\nDampak:\n1. Pengetahuan pentingnya tanaman.\n2. Keterampilan bercocok tanam.\n3. Karakter disiplin dan tanggung jawab.\n\nEvaluasi:\n1. Perubahan jenis tanaman H-4.\n2. Beberapa peserta tidak hadir.\n3. Kedisiplinan waktu panitia perlu ditingkatkan.",
    "link_proposal": "https://drive.google.com/file/d/1-us4XI7fh5G_T9JM3VqHrwFu4JmCFbYl/view",
    "link_lpj": "https://drive.google.com/file/d/1q2JPLtgET5iNhCGlOSYhWtdMR4QNHFhw/view",
    "link_dokumentasi": "https://drive.google.com/file/d/1w2pV6Yd_7aXZES8yjKmCMAeyea7TGBy_/view"
  },
  {
    "nama_proker": "Fin-Sight: Financial Insight",
    "divisi": "Divisi Pendidikan",
    "status": "DONE",
    "tanggal": "15 Oktober 2025 - 26 Februari 2026",
    "deskripsi": "Program peningkatan literasi ekonomi melalui konten edukatif di Instagram @genbi.upnvjt.",
    "description_long": "KPI:\nPublikasi rutin setiap bulan bergantian feed dan reel.\n\nDampak:\n1. Pemahaman isu ekonomi meningkat.\n2. Minat belajar ekonomi naik.\n3. Literasi keuangan masyarakat meningkat.\n\nEvaluasi:\nPerlu meningkatkan frekuensi pemantauan berita agar konten tetap up-to-date.",
    "link_proposal": "Menyusul",
    "link_lpj": "Tidak ada",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1OPL-7xuAIGasxjGHMSdoEGi3AJsNGfcO"
  },
  {
    "nama_proker": "GenBI COIN: Company Insight",
    "divisi": "Divisi Pendidikan",
    "status": "DONE",
    "tanggal": "2025-12-12",
    "deskripsi": "Kunjungan industri ke PT Kiwoom Sekuritas Indonesia untuk memahami ekosistem pasar modal.",
    "description_long": "KPI:\n1. Target 55 peserta hadir.\n2. Seluruh peserta membuka akun saham.\n\nDampak:\n1. Wawasan industri pasar modal.\n2. Kesiapan investasi meningkat.\n3. Jejaring kolaborasi antarlembaga.\n\nEvaluasi:\n1. Panitia kurang tepat waktu.\n2. Rundown molor 30 menit.\n3. Peserta tidak hadir tanpa konfirmasi.",
    "link_proposal": "Proposal GenBI COIN.pdf",
    "link_lpj": "https://drive.google.com/file/d/1uJN_kFxdYLseUgz-jzkqnxucuPLnQ4eW/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1ZziABWFSb6qdlwHhjpp_GyXCQP7YVPMz"
  },
  {
    "nama_proker": "GenBI SHINE: Sharing Health, Inspiring New Education",
    "divisi": "Divisi Pendidikan",
    "status": "DONE",
    "tanggal": "26 Oktober 2025, 29 November 2025",
    "deskripsi": "Program kolaboratif fokus pada literasi keuangan \"Belajar Rupiah Sejak Dini\" dan kesehatan anak.",
    "description_long": "KPI:\n1. Target 30 anak (26 Okt)\n2. Target 50 anak (29 Nov)\n\nDampak:\n1. Pemahaman mengenal rupiah.\n2. Kesadaran hidup bersih meningkat.\n3. Pembinaan berdampak di Kampung Anak Negeri.\n\nEvaluasi:\n1. Ketidaksesuaian data peserta.\n2. Panitia kurang sigap menyambut.\n3. Pembagian kelompok kurang sesuai usia.",
    "link_proposal": "Proposal GenBI SHINE.pdf",
    "link_lpj": "https://drive.google.com/file/d/15UpvSwgZyIAPHuOi9j8s_1U5LycXTSmp/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1FiDFWLVLYKl8-TcVFg6rgISZ1XAy4f9B"
  },
  {
    "nama_proker": "Future Scholars Talk: Webinar Tips & Trik Lolos Beasiswa BI 2026",
    "divisi": "Divisi Pendidikan",
    "status": "DONE",
    "tanggal": "2026-01-24",
    "deskripsi": "Webinar persiapan seleksi Beasiswa Bank Indonesia 2026 bersama alumni penerima beasiswa.",
    "description_long": "KPI:\n1. Target >300 peserta.\n2. Materi CV, Motivation Letter, dan Wawancara.\n\nDampak:\n1. Gambaran jelas strategi lolos.\n2. Kepercayaan diri peserta meningkat.\n3. Peluang lolos beasiswa lebih besar.\n\nEvaluasi:\n1. Gangguan jaringan internet.\n2. Rundown kurang sesuai rencana.\n3. Kelebihan realisasi anggaran pemateri.",
    "link_proposal": "Proposal Webinar Future Scholar Talk.pdf",
    "link_lpj": "https://drive.google.com/file/d/1Gohn9M-7Cy22JGYG8fOV3UpRkVx1XVTi/view",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1u5mtCwQVKcTjpwmN7UiY5sTWygFqFJeE"
  },
  {
    "nama_proker": "Biventure 2025",
    "divisi": "Divisi Hubungan Eksternal",
    "status": "DONE",
    "tanggal": "2026-11-25",
    "deskripsi": "Edukasi literasi kebanksentralan melalui kunjungan ke De Javasche Bank.",
    "description_long": "KPI:\n1. Minimal 70% kehadiran.\n2. Minimal 80% isi evaluasi.\n\nDampak:\n1. Mengenal sejarah uang.\n2. Memahami peran BI.\n3. Mendalami stabilitas ekonomi.\n\nEvaluasi:\n1. Keterlambatan pemateri.\n2. Kehadiran memenuhi target.\n3. Respons positif dari peserta.",
    "link_proposal": "Proposal BI Adventure.docx",
    "link_lpj": "LPJ BIVENTURE 2025 SIGNED.pdf",
    "link_dokumentasi": "Dokumentasi Biventure 2025"
  },
  {
    "nama_proker": "Genbi Connect",
    "divisi": "Divisi Hubungan Eksternal",
    "status": "DONE",
    "tanggal": "2026-02-07",
    "deskripsi": "Bootcamp kolaboratif peningkatan keterampilan Public Relations (PR) bagi generasi muda.",
    "description_long": "KPI:\n1. Target 35-50 peserta.\n2. Minimal 80% isi presensi.\n\nDampak:\n1. Memahami peran strategis PR.\n2. Praktik komunikasi efektif.\n3. Kesiapan menghadapi tantangan organisasi.\n\nEvaluasi:\nMenyusul",
    "link_proposal": "Proposal Digital GenBI Connect 2026.pdf",
    "link_lpj": "Menyusul",
    "link_dokumentasi": "Genbi Connect"
  },
  {
    "nama_proker": "Inspire Talk",
    "divisi": "Divisi Hubungan Eksternal",
    "status": "ON_PROGRESS",
    "tanggal": "2026-02-28",
    "deskripsi": "Workshop adaptif untuk membangun kompetensi generasi muda di era digital.",
    "description_long": "KPI:\n1. Target 50-80 peserta.\n2. Minimal 80% isi evaluasi.\n\nDampak:\n1. Wawasan dunia modern.\n2. Kapasitas personal meningkat.\n3. Citra positif GenBI.\n\nEvaluasi:\nMenyusul",
    "link_proposal": "Menyusul",
    "link_lpj": "Menyusul",
    "link_dokumentasi": "Menyusul"
  },
  {
    "nama_proker": "Genbi Scale - Workshop Digitalisasi UMKM",
    "divisi": "Divisi Ekonomi Kreatif",
    "status": "DONE",
    "tanggal": "2026-01-10",
    "deskripsi": "Workshop foto produk dan promosi online untuk UMKM binaan Kelurahan Medokan Ayu.",
    "description_long": "KPI:\nRealisasi 25 pelaku UMKM (Target awal 20).\n\nDampak:\nMeningkatkan keterampilan foto produk dan pemanfaatan AI (Google Gemini) untuk strategi pemasaran digital.\n\nEvaluasi:\nMateri relevan dan peserta antusias, namun koordinasi internal panitia perlu ditingkatkan.",
    "link_proposal": "PROPOSAL GENBI SCALE.pdf",
    "link_lpj": "LPJ GENBI SCALE.pdf",
    "link_dokumentasi": "Genbi Scale"
  },
  {
    "nama_proker": "Pelita (Bucket Bunga X PSDM)",
    "divisi": "Divisi Ekonomi Kreatif",
    "status": "DONE",
    "tanggal": "2026-02-14",
    "deskripsi": "Program kreatif pembuatan bunga dari kawat bulu untuk meningkatkan keterampilan mahasiswa GenBI.",
    "description_long": "KPI:\nSeluruh mahasiswa GenBI UPN \"Veteran\" Jawa Timur.\n\nDampak:\n1. Pengembangan keterampilan buket bunga.\n2. Rasa kebersamaan antaranggota.\n3. Peluang usaha ekonomi kreatif.\n\nEvaluasi:\nPersiapan photo booth memakan waktu lama sehingga pembukaan acara mundur.",
    "link_proposal": "PROPOSAL PELITA.pdf",
    "link_lpj": "LPJ PELITA.pdf",
    "link_dokumentasi": "GenBI Pelita"
  }
];
