export const prokerUnugiriData = [
  {
    "divisi": "BPH",
    "nama_proker": "Makrab Anggota GenBI Komisariat UNUGIRI",
    "tanggal": "2026-04-19",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "\"Tidak Ada Proposal\"",
    "deskripsi": "Makrab Anggota GenBI UNUGIRI ditujukan untuk mempererat kembali\nkekompakan pengurus di periode kepengurusan. Kegiatan ini berisi\npenguatan bonding, evaluasi program kerja yang sudah berlangsung, dan\ndiskusi ringan untuk menyamakan kembali arah dan semangat kerja.\nMelalui Makrab, diharapkan tercipta suasana yang lebih solid dan\nkomunikatif dalam menyelesaikan sisa program kerja periode ini.",
    "kpi": "1. Minimal 90% pengurus hadir dan mengikuti seluruh rangkaian kegiatan.\n2. Ada sesi evaluasi dan diskusi tengah periode dengan hasil yang\ndapat ditindaklanjuti.\n3. Terbangunnya kembali kekompakan dan komunikasi kerja antar\npengurus.\n4. Tersusunnya poin perbaikan untuk pelaksanaan proker pada sisa \nperiode.",
    "dampak": "1. Kekompakan dan rasa kebersamaan pengurus meningkat kembali.\n2. Komunikasi internal menjadi lebih efektif and terbuka.\n3. Koordinasi pelaksanaan proker berikutnya menjadi lebih lancar.\n4. Semangat dan motivasi pengurus meningkat untuk menyelesaikan sisa\nprogram kerja periode ini.",
    "evaluasi": "Menyusul",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1nf1YjxIOmYcSYGJoZcXyLyPD3PH71BWk?usp=sharing",
    "link_lpj": "\"Tidak Ada LPJ\"",
    "description_long": "KPI: 1. Minimal 90% pengurus hadir dan mengikuti seluruh rangkaian kegiatan.\n2. Ada sesi evaluasi dan diskusi tengah periode dengan hasil yang\ndapat ditindaklanjuti.\n3. Terbangunnya kembali kekompakan dan komunikasi kerja antar\npengurus.\n4. Tersusunnya poin perbaikan untuk pelaksanaan proker pada sisa \nperiode.\n\nDampak: 1. Kekompakan dan rasa kebersamaan pengurus meningkat kembali.\n2. Komunikasi internal menjadi lebih efektif and terbuka.\n3. Koordinasi pelaksanaan proker berikutnya menjadi lebih lancar.\n4. Semangat dan motivasi pengurus meningkat untuk menyelesaikan sisa\nprogram kerja periode ini.\n\nEvaluasi: Menyusul"
  },
  {
    "divisi": "SOSMA",
    "nama_proker": "GenBI Healthy",
    "tanggal": "2025-11-09",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/drive/folders/1vDvApDhrocZGUGqrStxxtleHv17-NFuo",
    "deskripsi": "GenBI Healthy merupakan program donor darah yang berkolaborasi dengan Palang Merah Indonesia (PMI) Bojonegoro, dengan tema \"Setetes Darah, Berjuta Manfaat\"",
    "kpi": "Peserta kegiatan adalah seluruh elemen masyarakat yang mau berdonor, Mahasiswa / Pelajar, Anggota GenBI Komisariat UNUGIRI",
    "dampak": "Program ini meningkatkan kesadaran akan pentingnya kesehatan, menambah stok darah untuk kebutuhan medis, menginspirasi gerakan kesehatan nasional, mendorong partisipasi aktif dalam aksi sosial, dan mendukung gaya hidup sehat.",
    "evaluasi": "1. Kegiatan terlaksana dengan lancar; 2. Peserta memberikan respon positif; 3. Tingkat kehadiran tinggi, sekitar 30-35 peserta; 4. Terdapat kendala kecil, seperti beberapa pendonor tidak memperoleh souvenir, tapi dapat diatasi dengan baik",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1GVMJzWyZVYxr0q2ZQUM4-5TbbFfgSpiw",
    "link_lpj": "https://drive.google.com/drive/folders/1lyX8ErFDbb5b0Ufk8RhTV6N3_GdLZFhU",
    "description_long": "KPI: Peserta kegiatan adalah seluruh elemen masyarakat yang mau berdonor, Mahasiswa / Pelajar, Anggota GenBI Komisariat UNUGIRI\n\nDampak: Program ini meningkatkan kesadaran akan pentingnya kesehatan, menambah stok darah untuk kebutuhan medis, menginspirasi gerakan kesehatan nasional, mendorong partisipasi aktif dalam aksi sosial, dan mendukung gaya hidup sehat.\n\nEvaluasi: 1. Kegiatan terlaksana dengan lancar; 2. Peserta memberikan respon positif; 3. Tingkat kehadiran tinggi, sekitar 30-35 peserta; 4. Terdapat kendala kecil, seperti beberapa pendonor tidak memperoleh souvenir, tapi dapat diatasi dengan baik"
  },
  {
    "divisi": "SOSMA",
    "nama_proker": "Bakti Sosial \"GenBI Cerdas, GenBI Peduli: Sehari Berbagi \nIlmu, Selamanya Berbagi Kasih\"",
    "tanggal": "2025-12-28",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/drive/folders/1SnhgIfqpeWbilS74e_hWgu4O_ZUdHd6J",
    "deskripsi": "Program kegiatan ini nantinya akan berkolaborasi dengan Yayasan Panti Asuhan di daerah Bojonegoro, di dalam acara nantinya akan diisi dengan seminar CBP oleh anggota genbi sendiri and hiburan dari Pantonim Bojonegoro. Nantinya di akhir acara akan diadakan penyerahan santunan/donasi dari GenBI Komisariat Unugiri kepada Yayasan Panti Asuhan",
    "kpi": "1. Anak-anak panti; 2. Perwakilan masing-masing devisi dari GenBI komisariat Unugiri",
    "dampak": "1. Mencerdaskan dan Memotivasi masyarakat sasaran melalui transfer ilmu \npengetahuan dan keterampilan\n2. Mengimplementasikan Peran Duta BI dengan menyampaikan literasi \nkebanksentralan dan keuangan dasar (Cinta, Bangga, Paham Rupiah) kepada \nmasyarakat.\n3. Mewujudkan Tanggung Jawab Sosial GenBI sebagai bentuk pengabdian kepada \nmasyarakat (Tri Dharma Perguruan Tinggi).\n4. Membangun Solidaritas dan Kepedulian yang berkelanjutan antara GenBI dengan\nmasyarakat penerima manfaat khususnya bagi Pihak Panti Yayasan Karya Binangun\nMandiri",
    "evaluasi": "1. Kegiatan terlaksana dengan lancar; 2. Peserta yang hadir sekitar 20-25 anak",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1s-AXA3jwc-6psERQ6daEL7K06OawyYcQ",
    "link_lpj": "https://drive.google.com/drive/folders/1SnhgIfqpeWbilS74e_hWgu4O_ZUdHd6J",
    "description_long": "KPI: 1. Anak-anak panti; 2. Perwakilan masing-masing devisi dari GenBI komisariat Unugiri\n\nDampak: 1. Mencerdaskan dan Memotivasi masyarakat sasaran melalui transfer ilmu \npengetahuan dan keterampilan\n2. Mengimplementasikan Peran Duta BI dengan menyampaikan literasi \nkebanksentralan dan keuangan dasar (Cinta, Bangga, Paham Rupiah) kepada \nmasyarakat.\n3. Mewujudkan Tanggung Jawab Sosial GenBI sebagai bentuk pengabdian kepada \nmasyarakat (Tri Dharma Perguruan Tinggi).\n4. Membangun Solidaritas dan Kepedulian yang berkelanjutan antara GenBI dengan\nmasyarakat penerima manfaat khususnya bagi Pihak Panti Yayasan Karya Binangun\nMandiri\n\nEvaluasi: 1. Kegiatan terlaksana dengan lancar; 2. Peserta yang hadir sekitar 20-25 anak"
  },
  {
    "divisi": "LH",
    "nama_proker": "GenBI ECC UNUGIRI 2025",
    "tanggal": "2025-10-15",
    "format": "Hybrid",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/file/d/1lDeUeFylUVRl66Rv3jLfH8sUqfzQNsu2/view?usp=drivesdk",
    "deskripsi": "Eco Challenge merupakan program kerja berupa\nlomba video kreatif dengan tema Eco Friendly Edition.\nKegiatan ini bertujuan untuk mengajak peserta\nmenyalurkan ide dan kreativitas dalam bentuk karya\ndigital yang berisi ajakan, edukasi, atau aksi nyata\nmenjaga kelestarian alam.",
    "kpi": "1. Peserta merupakan mahasiswa aktif dari Universitas Nahdlatul Ulama Sunan Giri maupun dari PTN/PTS lain.\n2. Lomba bersifat individu.\n3. Setiap peserta membuat 1 video berdurasi minimal 2 menit.\n4. Video wajib menampilkan aksi nyata sesuai indikator Go Clean, Go Green, Go Sustainable.\n5. Peserta wajib mengikuti seluruh rangkaian kegiatan sesuai timeline.\n6. Video harus merupakan karya orisinal, tidak mengandung unsur SARA, kekerasan, atau pornografi.\n7. Peserta wajib menaati seluruh peraturan lomba.",
    "dampak": "Program ini meningkatkan kesadaran mahasiswa terhadap isu lingkungan dan mendorong mereka untuk lebih peduli pada kelestarian alam melalui penyampaian pesan edukatif dalam bentuk video kreatif. Selain itu, program ini juga membuka ruang partisipasi publik kampus dalam kampanye digital bertema lingkungan.",
    "evaluasi": "Jumlah video masuk: 10 video\nJumlah peserta yang terlibat: 17\nPemenang diambil juara 1, 2, 3",
    "link_dokumentasi": "https://drive.google.com/folderview?id=14Kl3oNqPaZ5kcQevH1qbA9lIiDPwA-gk",
    "link_lpj": "https://docs.google.com/document/d/13lwIgGEB6QHn3mF_oIbHG-fbw20ZMqfw/edit?usp=drivesdk&ouid=102989470977958967481&rtpof=true&sd=true",
    "description_long": "KPI: 1. Peserta merupakan mahasiswa aktif dari Universitas Nahdlatul Ulama Sunan Giri maupun dari PTN/PTS lain.\n2. Lomba bersifat individu.\n3. Setiap peserta membuat 1 video berdurasi minimal 2 menit.\n4. Video wajib menampilkan aksi nyata sesuai indikator Go Clean, Go Green, Go Sustainable.\n5. Peserta wajib mengikuti seluruh rangkaian kegiatan sesuai timeline.\n6. Video harus merupakan karya orisinal, tidak mengandung unsur SARA, kekerasan, atau pornografi.\n7. Peserta wajib menaati seluruh peraturan lomba.\n\nDampak: Program ini meningkatkan kesadaran mahasiswa terhadap isu lingkungan dan mendorong mereka untuk lebih peduli pada kelestarian alam melalui penyampaian pesan edukatif dalam bentuk video kreatif. Selain itu, program ini juga membuka ruang partisipasi publik kampus dalam kampanye digital bertema lingkungan.\n\nEvaluasi: Jumlah video masuk: 10 video\nJumlah peserta yang terlibat: 17\nPemenang diambil juara 1, 2, 3"
  },
  {
    "divisi": "LH",
    "nama_proker": "GenBI Reboisasi",
    "tanggal": "2026-01-22",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/file/d/19LzEphShlp4SpsfxSN96IPW9WFX64-Nm/view?usp=drivesdk",
    "deskripsi": "Reboisasi GenBI Unugiri: \"Hijaukan Bumi, Lestarikan Alam\" Menggalakkan kesadaran lingkungan dan meningkatkan kualitas lingkungan hidup melalui penanaman pohon and reboisasi.",
    "kpi": "Pohon yang digunakan untuk reboisasi adalah Kayu Putih\nSasaran seluruh anggota GenBI Unugiri\nLokasi pelaksanaan di Ds. Ngunut, Kec. Dander (lahan perhutani",
    "dampak": "Melalui kegiatan reboisasi, diharapkan apat memulihkan, meningkatkan, sekaligus menjaga fungsi ekologis kelestarian lingkungan pada suatu kawasan.",
    "evaluasi": "Menyusul",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1O7wxmJ_32ZffSoQ4q_ehKWiUEpRbb44x",
    "link_lpj": "https://drive.google.com/file/d/1g8zr0Fd0O_9SEYTIbGAjCuoc51QCgDO_/view?usp=drivesdk",
    "description_long": "KPI: Pohon yang digunakan untuk reboisasi adalah Kayu Putih\nSasaran seluruh anggota GenBI Unugiri\nLokasi pelaksanaan di Ds. Ngunut, Kec. Dander (lahan perhutani\n\nDampak: Melalui kegiatan reboisasi, diharapkan apat memulihkan, meningkatkan, sekaligus menjaga fungsi ekologis kelestarian lingkungan pada suatu kawasan.\n\nEvaluasi: Menyusul"
  },
  {
    "divisi": "KWU",
    "nama_proker": "GenBI Enterpreneur “Wirausaha Muda Inovatif untuk Ekonomi Bangsa”",
    "tanggal": "2025-10-27",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/file/d/1JNIkwvV_Lleu5ADkID139804TllxF_qk/view?usp=drive_link",
    "deskripsi": "Kegiatan GenBI Entrepreneur adalah program pembinaan kewirausahaan bagi anggota GenBI untuk mengembangkan kreativitas, keterampilan bisnis, and inovasi guna mencetak wirausaha muda yang berdaya saing dan berdampak bagi perekonomian.",
    "kpi": "Peserta kegiatan GenBI Entrepreneur adalah seluruh anggota Divisi Kewirausahaan GenBI Komisariat UNUGIRI tahun 2025. Dan sasaran kegiatan ini adalah anggota GenBI yang berminat dan berpotensi dalam bidang kewirausahaan, serta generasi muda yang ingin mengembangkan ide bisnis inovatif dan keterampilan usaha.",
    "dampak": "Kegiatan ini memberikan dampak berupa meningkatnya kemampuan dan wawasan kewirausahaan anggota GenBI, tumbuhnya ide bisnis yang inovatif, serta terbentuknya jiwa kemandirian dan kreativitas dalam berusaha. Selain itu, kegiatan ini mendorong terciptanya generasi muda yang lebih produktif dan mampu berkontribusi pada pertumbuhan ekonomi masyarakat.",
    "evaluasi": "1. Lokasi kurang strategis sehingga pengunjung sedikit. 2. Penjualan tidak maksimal karena area kegiatan sepi. 3. Sisa produk dibagikan kepada satpam dan anggota Banser di sekitar lokasi.",
    "link_dokumentasi": "https://drive.google.com/drive/folders/19qKE-ud7drnMIn9Nh3Me__eP1auL_Fqn?usp=drive_link",
    "link_lpj": "https://docs.google.com/document/d/1j3A8NEHrk7eIzb6WJZlf2JU0tCxmLS4r/edit?usp=drive_link&ouid=117153588717189062918&rtpof=true&sd=true",
    "description_long": "KPI: Peserta kegiatan GenBI Entrepreneur adalah seluruh anggota Divisi Kewirausahaan GenBI Komisariat UNUGIRI tahun 2025. Dan sasaran kegiatan ini adalah anggota GenBI yang berminat dan berpotensi dalam bidang kewirausahaan, serta generasi muda yang ingin mengembangkan ide bisnis inovatif dan keterampilan usaha.\n\nDampak: Kegiatan ini memberikan dampak berupa meningkatnya kemampuan dan wawasan kewirausahaan anggota GenBI, tumbuhnya ide bisnis yang inovatif, serta terbentuknya jiwa kemandirian dan kreativitas dalam berusaha. Selain itu, kegiatan ini mendorong terciptanya generasi muda yang lebih produktif dan mampu berkontribusi pada pertumbuhan ekonomi masyarakat.\n\nEvaluasi: 1. Lokasi kurang strategis sehingga pengunjung sedikit. 2. Penjualan tidak maksimal karena area kegiatan sepi. 3. Sisa produk dibagikan kepada satpam dan anggota Banser di sekitar lokasi."
  },
  {
    "divisi": "KWU",
    "nama_proker": "G-SMART QRIS (GenBI – Sosialisasi Mandiri & Akses Retail QRIS)",
    "tanggal": "2026-01-10",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "\"Tidak Ada Proposal\"",
    "deskripsi": "Program sosialisasi QRIS bertujuan membantu pemilik toko, warung, and UMKM memahami serta menggunakan pembayaran digital. Kegiatan ini meliputi edukasi tentang QRIS, manfaatnya bagi perkembangan usaha, serta pendampingan langsung dalam proses pendaftaran dan penggunaan. Melalui sosialisasi ini, pelaku usaha diharapkan lebih siap beradaptasi dengan transaksi non-tunai dan mampu meningkatkan efisiensi serta peluang usaha.",
    "kpi": "Target kegiatan ini adalah pemilik toko, warung, dan pelaku UMKM yang belum memiliki atau belum memahami penggunaan QRIS agar mereka mampu beradaptasi dengan sistem pembayaran digital secara mudah dan mandiri.",
    "dampak": "Kegiatan ini berdampak pada meningkatnya pemahaman pelaku usaha mengenai pembayaran digital, memudahkan proses transaksi, serta memperluas peluang penjualan. Dengan memiliki dan menggunakan QRIS, pemilik toko, warung, and UMKM menjadi lebih siap bersaing, lebih efisien dalam melayani pelanggan, and mampu mengikuti perkembangan ekonomi digital secara berkelanjutan.",
    "evaluasi": "1. Kegiatan berjalan lancar dan sesuai tujuan sosialisasi QRIS kepada pemilik toko, warung, dan pelaku UMKM.\n2. Antusiasme pelaku sasaran cukup tinggi, terutama saat sesi praktik langsung pendaftaran dan penggunaan QRIS.\n3. Terdapat UMKM yang sebelumnya sudah didata untuk dibuatkan QRIS, namun pada hari pelaksanaan sulit dihubungi sehingga proses pendampingan dan pendaftaran tidak dapat dilakukan secara maksimal.",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1aMWZ8_Lbz9sHRL19moN_qjDpycGrAbQs",
    "link_lpj": "\"Tidak Ada LPJ\"",
    "description_long": "KPI: Target kegiatan ini adalah pemilik toko, warung, dan pelaku UMKM yang belum memiliki atau belum memahami penggunaan QRIS agar mereka mampu beradaptasi dengan sistem pembayaran digital secara mudah dan mandiri.\n\nDampak: Kegiatan ini berdampak pada meningkatnya pemahaman pelaku usaha mengenai pembayaran digital, memudahkan proses transaksi, serta memperluas peluang penjualan. Dengan memiliki dan menggunakan QRIS, pemilik toko, warung, and UMKM menjadi lebih siap bersaing, lebih efisien dalam melayani pelanggan, and mampu mengikuti perkembangan ekonomi digital secara berkelanjutan.\n\nEvaluasi: 1. Kegiatan berjalan lancar dan sesuai tujuan sosialisasi QRIS kepada pemilik toko, warung, dan pelaku UMKM.\n2. Antusiasme pelaku sasaran cukup tinggi, terutama saat sesi praktik langsung pendaftaran dan penggunaan QRIS.\n3. Terdapat UMKM yang sebelumnya sudah didata untuk dibuatkan QRIS, namun pada hari pelaksanaan sulit dihubungi sehingga proses pendampingan dan pendaftaran tidak dapat dilakukan secara maksimal."
  },
  {
    "divisi": "PENDIDIKAN",
    "nama_proker": "TALKSHOW LITERASI PENGELOLAAN CASH MANAGEMENT",
    "tanggal": "2025-12-06",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/file/d/1CAWmPxJ2HS-u-eS_bqvlLjXJRcon3i4P/view?usp=sharing",
    "deskripsi": "\"Seminar CBP Rupiah (Cinta, Bangga, Paham Rupiah) merupakan program kerja Divisi Pendidikan GenBI Unugiri yang bertujuan untuk meningkatkan literasi mahasiswa terkait peran Rupiah sebagai simbol kedaulatan negara dan alat pembayaran yang sah. Melalui seminar ini, peserta akan diberikan edukasi mengenai pentingnya mencintai Rupiah sebagai identitas bangsa, menumbuhkan rasa bangga melalui pemahaman sejarah, desain, and nilai filosofis Rupiah, serta memahami ciri keaslian uang rupiah guna mencegah peredaran uang palsu.\nKegiatan ini menghadirkan narasumber dari Bank Indonesia atau pihak kompeten lainnya yang akan memaparkan materi secara interaktif mengenai sistem pembayaran, penggunaan Rupiah dalam transaksi tunai maupun non-tunai, serta pentingnya menjaga Rupiah sebagai bentuk dukungan terhadap stabilitas ekonomi nasional.\nSeminar dikemas dengan sesi tanya jawab, diskusi, and pembagian doorprize untuk meningkatkan keterlibatan peserta. Peserta seminar merupakan mahasiswa aktif yang diharapkan mampu menjadi agen edukasi dalam lingkungan sosialnya. Melalui program ini, GenBI berkomitmen mendukung kampanye Bank Indonesia dalam memperluas pemahaman CBP Rupiah kepada generasi muda.\"",
    "kpi": "\"Jumlah peserta minimal 100 mahasiswa.\nTingkat pemahaman peserta meningkat (diukur melalui pre-test & post-test).\n80% peserta aktif dalam sesi diskusi/tanya jawab.\nPublikasi seminar menjangkau minimal 5 platform (IG feed, IG story, WA, website kampus, poster).\nTerlaksananya kerja sama dengan pemateri dari BI atau pihak relevan.\"",
    "dampak": "Meningkatnya literasi mahasiswa tentang CBP Rupiah.\nPeserta mampu mengenali ciri keaslian rupiah and menghindari uang palsu.\nTerbentuknya sikap cinta and bangga terhadap Rupiah sebagai identitas bangsa.\nMahasiswa lebih bijak dalam bertransaksi tunai maupun non-tunai.\nMendukung kampanye Bank Indonesia dalam menjaga kedaulatan Rupiah",
    "evaluasi": "Melakukan pre-test and post-test untuk mengukur peningkatan literasi peserta.\nMengumpulkan feedback melalui Google Form terkait kepuasan peserta.\nEvaluasi internal panitia mengenai alur acara, publikasi, and teknis pelaksanaan.\nMenyusun laporan akhir kegiatan sebagai dasar perbaikan program berikutnya",
    "link_dokumentasi": "https://drive.google.com/file/d/1aBkCgqWlqM5GbdMDRUZ_spgARm-ZSpyU/view?usp=sharing",
    "link_lpj": "https://drive.google.com/file/d/1-h38lPfpCuGl9SxkECSBMTukE1_R0YK1/view?usp=sharing",
    "description_long": "KPI: \"Jumlah peserta minimal 100 mahasiswa.\nTingkat pemahaman peserta meningkat (diukur melalui pre-test & post-test).\n80% peserta aktif dalam sesi diskusi/tanya jawab.\nPublikasi seminar menjangkau minimal 5 platform (IG feed, IG story, WA, website kampus, poster).\nTerlaksananya kerja sama dengan pemateri dari BI atau pihak relevan.\"\n\nDampak: Meningkatnya literasi mahasiswa tentang CBP Rupiah.\nPeserta mampu mengenali ciri keaslian rupiah and menghindari uang palsu.\nTerbentuknya sikap cinta and bangga terhadap Rupiah sebagai identitas bangsa.\nMahasiswa lebih bijak dalam bertransaksi tunai maupun non-tunai.\nMendukung kampanye Bank Indonesia dalam menjaga kedaulatan Rupiah\n\nEvaluasi: Melakukan pre-test and post-test untuk mengukur peningkatan literasi peserta.\nMengumpulkan feedback melalui Google Form terkait kepuasan peserta.\nEvaluasi internal panitia mengenai alur acara, publikasi, and teknis pelaksanaan.\nMenyusun laporan akhir kegiatan sebagai dasar perbaikan program berikutnya"
  },
  {
    "divisi": "PENDIDIKAN",
    "nama_proker": "GenBI Mengajar",
    "tanggal": "2026-01-13",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/file/d/1ItRXrtoAnswnrhwuPdxmtbInMnLBKTgG/view?usp=sharing",
    "deskripsi": "Kegiatan Gen BI Mengajar ini bertujuan untuk:\n1. Meningkatkan Literasi Finansial bagi peserta didik.\n2. Membekali Peserta dengan pengetahuan dasar tentang pengelolaan anggaran, menabung, and risiko pinjaman.\n3. Mendorong Peserta untuk mengadopsi kebiasaan finansial yang cerdas dan bertanggung jawab.\n4. Menghargai dan memberikan pengakuan kepada pihak sekolah/guru yang telah mendukung upaya edukasi literasi finansial",
    "kpi": "Peserta kegiatan Gen BI Mengajar ini adalah siswa/i MA.Rahmatullah, Desa Tulungagung, Kec. Baureno,\n Kab. Bojonegoro yang berjumlah sekitar 70 orang",
    "dampak": "meningkatkan pemahaman and keterampilan praktis peserta didik dalam mengelola keuangan pribadi",
    "evaluasi": "- Kendala: Terdapat sedikit hambatan teknis pada peralatan (proyektor) and manajemen waktu yang menyebabkan durasi materi sedikit berkurang.\n\n- Solusi: Kedepannya perlu dilakukan pengecekan lokasi (cek alat) lebih awal and penambahan simulasi permainan agar materi lebih interaktif.\n\n- Keberhasilan: Target peserta sebanyak 70 siswa tercapai and anggaran sebesar Rp 1.000.000 terserap secara efektif sesuai rencana",
    "link_dokumentasi": "https://drive.google.com/file/d/1pC3Q6jmpU_2NzsxhfqT3bftKZ6idhG9w/view?usp=sharing",
    "link_lpj": "https://drive.google.com/file/d/1n4qFiPmf29RnCoM-gHmCjwNQjK9WJxpT/view?usp=sharing",
    "description_long": "KPI: Peserta kegiatan Gen BI Mengajar ini adalah siswa/i MA.Rahmatullah, Desa Tulungagung, Kec. Baureno,\n Kab. Bojonegoro yang berjumlah sekitar 70 orang\n\nDampak: meningkatkan pemahaman and keterampilan praktis peserta didik dalam mengelola keuangan pribadi\n\nEvaluasi: - Kendala: Terdapat sedikit hambatan teknis pada peralatan (proyektor) and manajemen waktu yang menyebabkan durasi materi sedikit berkurang.\n\n- Solusi: Kedepannya perlu dilakukan pengecekan lokasi (cek alat) lebih awal and penambahan simulasi permainan agar materi lebih interaktif.\n\n- Keberhasilan: Target peserta sebanyak 70 siswa tercapai and anggaran sebesar Rp 1.000.000 terserap secara efektif sesuai rencana"
  },
  {
    "divisi": "MEDINFO",
    "nama_proker": "Seminar Branding Digital",
    "tanggal": "2025-12-06",
    "format": "Offline",
    "status": "DONE",
    "link_proposal": "https://drive.google.com/drive/folders/1eQRuiJZQVGx_TM2fB9z5_vCxFQTXnRE5",
    "deskripsi": "Seminar Branding Digital dengan tema sentral \"Digital Authority: Strategi Pemanfaatan Media Sosial untuk Membangun Brand Value Organisasi dan Personal Credibility\". Kegiatan ini dirancang secara khusus untuk menjembatani kesenjangan antara kesadaran akan pentingnya digitalisasi dengan keterampilan praktis yang diperlukan. Seminar ini bertujuan untuk memberikan panduan komprehensif tentang cara merumuskan strategi konten yang berdampak, mengoptimalkan platform media sosial untuk pertumbuhan, and mempertahankan etika digital dalam setiap interaksi.",
    "kpi": "1.Peserta merupakan Mahasiswa/i aktif  UNUGIRI Bojonegoro serta delegasi per Ormawa UNUGIRI Bojonegoro  yang berjumlah 150                2. diantaranya 100 peserta umum mahasiswa/i UNUGIRI,50 Pesers delegasi Ormawa UNUGIRI",
    "dampak": "peserta seminar akan menjadi motor penggerak yang mampu mentransfer pengetahuan ini ke dalam lingkungan mereka, baik di organisasi, kampus, maupun komunitas profesional. Dampak jangka panjang yang diharapkan adalah terciptanya ekosistem digital yang sehat, di mana baik Brand Value organisasi maupun Personal Credibility individu dapat berkembang secara sinergis, berkontribusi pada citra positif organisasi secara keseluruhan, and pada akhirnya, memperluas dampak positif GenBI dalam mendukung pembangunan bangsa",
    "evaluasi": "Menyusul",
    "link_dokumentasi": "https://drive.google.com/drive/folders/1HZqZaDquYozkzFNbb8BnSSWMXOf2owUK",
    "link_lpj": "https://drive.google.com/file/d/1C9U9QvV8j3E4tpVSJZpN_RpqkasKrU_O/view?usp=drivesdk",
    "description_long": "KPI: 1.Peserta merupakan Mahasiswa/i aktif  UNUGIRI Bojonegoro serta delegasi per Ormawa UNUGIRI Bojonegoro  yang berjumlah 150                2. diantaranya 100 peserta umum mahasiswa/i UNUGIRI,50 Pesers delegasi Ormawa UNUGIRI\n\nDampak: peserta seminar akan menjadi motor penggerak yang mampu mentransfer pengetahuan ini ke dalam lingkungan mereka, baik di organisasi, kampus, maupun komunitas profesional. Dampak jangka panjang yang diharapkan adalah terciptanya ekosistem digital yang sehat, di mana baik Brand Value organisasi maupun Personal Credibility individu dapat berkembang secara sinergis, berkontribusi pada citra positif organisasi secara keseluruhan, and pada akhirnya, memperluas dampak positif GenBI dalam mendukung pembangunan bangsa\n\nEvaluasi: Menyusul"
  },
  {
    "divisi": "MEDINFO",
    "nama_proker": "Social Media Maintenance",
    "tanggal": "contoh: Minggu, 1 Februari 2026",
    "format": "Online",
    "status": "DONE",
    "link_proposal": "\"Tidak Ada Proposal\"",
    "deskripsi": "Program kerja ini berfokus pada pemeliharaan, pembaruan, serta optimalisasi seluruh akun media sosial organisasi agar tetap aktif, informatif, and menarik. Kegiatan ini mencakup manajemen konten, konsistensi unggahan, peningkatan engagement, serta evaluasi performa berdasarkan data insight.",
    "kpi": "Peningkatan engagement rate antaranggota\nKonsistensi posting sesuai kalender konten\nKeterlibatan anggota dalam challenge / interaksi post\nPeningkatan awareness program internal (jumlah views & reshare)\nVisual & tone of voice yang seragam di seluruh unggahan",
    "dampak": "Peningkatan Branding GenBI UNUGIRI: GenBI memiliki citra and reputasi yang lebih baik di mata kampus and luar kampus melalui media sosial yang dikelola dengan baik.\nKeterampilan and Kualitas Konten: Anggota komunitas GenBI memiliki keterampilan yang lebih baik dalam menciptakan konten yang menarik and relevan, sehingga meningkatkan kualitas konten yang dipublikasikan and memperkuat hubungan dengan pengikut media sosial.\nMemberikan Pengaruh Positif: GenBI menjadi contoh yang baik bagi komunitas lain dalam mengelola media sosial yang efektif and berkualitas, serta meningkatkan interaksi and engagement di media sosial.",
    "evaluasi": "Menyusul",
    "link_dokumentasi": "Menyusul",
    "link_lpj": "Menyusul",
    "description_long": "KPI: Peningkatan engagement rate antaranggota\nKonsistensi posting sesuai kalender konten\nKeterlibatan anggota dalam challenge / interaksi post\nPeningkatan awareness program internal (jumlah views & reshare)\nVisual & tone of voice yang seragam di seluruh unggahan\n\nDampak: Peningkatan Branding GenBI UNUGIRI: GenBI memiliki citra and reputasi yang lebih baik di mata kampus and luar kampus melalui media sosial yang dikelola dengan baik.\nKeterampilan and Kualitas Konten: Anggota komunitas GenBI memiliki keterampilan yang lebih baik dalam menciptakan konten yang menarik and relevan, sehingga meningkatkan kualitas konten yang dipublikasikan and memperkuat hubungan dengan pengikut media sosial.\nMemberikan Pengaruh Positif: GenBI menjadi contoh yang baik bagi komunitas lain dalam mengelola media sosial yang efektif and berkualitas, serta meningkatkan interaksi and engagement di media sosial.\n\nEvaluasi: Menyusul"
  }
]
