export const prokerItsData = [
  {
    "Divisi": "Public Relation",
    "Nama Proker": "GenBI Collaboration Forum",
    "Tanggal Proker": "contoh: Minggu, 1 Februari 2026",
    "Format Pelaksanaan": "",
    "Status": "",
    "Link Proposal": "",
    "Deskripsi Proker": "Forum reguler dengan komisariat GenBI UNESA dan GenBI UB untuk berbagi informasi kepada kedua komisariat. Forum dilaksanakan dengan cara focus-group discussion dan cross-group study case, yang ditutup dengan games untuk mempererat hubungan antar kedua komisariat.",
    "KPI/TUK/Target": "1. Terjalannya GenBI Collaboration Forum selama 1 kepengurusan : 2\n2. Persentase anggota pengurus komisariat GenBI ITS yang hadir pada acara : 50%\n3. Nilai rata-rata hasil feedback GenBI Collaboration Forum : 80",
    "Dampak": "Meningkatkan kolaborasi, bertukar informasi, dan memperkuat relasi antara GenBI ITS dengan komisariat GenBI UNESA dan GenBI UB.",
    "Evaluasi": "",
    "Dokumentasi (Link Drive)": "",
    "Link LPJ": ""
  },
  {
    "Divisi": "Public Relation",
    "Nama Proker": "Sosialisasi Beasiswa Bank Indonesia",
    "Tanggal Proker": "contoh: Minggu, 1 Februari 2026",
    "Format Pelaksanaan": "",
    "Status": "",
    "Link Proposal": "",
    "Deskripsi Proker": "Sosialisasi program Beasiswa Bank Indonesia sebagai media penyampaian informasi kepada mahasiswa ITS mengenai cara dan tips bagi yang berminat pada program tersebut.",
    "KPI/TUK/Target": "1. Terjalannnya Sosialisasi Beasiswa Bank Indonesia dalam 1 kepengurusan : 1\n2. Jumlah peserta yang hadir dalam sosialisasi : 75 orang",
    "Dampak": "Menarik minat mahasiswa ITS angkatan 2023 dan 2024 untuk mendaftar beasiswa Bank Indonesia dengan memberi informasi yang memudahkan dalam menjalani proses seleksi beasiswa Bank Indonesia.",
    "Evaluasi": "",
    "Dokumentasi (Link Drive)": "",
    "Link LPJ": ""
  },
  {
    "Divisi": "Organizational Development",
    "Nama Proker": "Company Visit 1",
    "Tanggal Proker": "2025-12-02",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal Company Visit",
    "Deskripsi Proker": "Program kerja ini bekerja sama dengan Otoritas Jasa Keuangan, sehingga GenBI ITS memahami lebih dalam tentang OJK",
    "KPI/TUK/Target": "88 orang",
    "Dampak": "GenBI ITS mampu memahami lebih dalam tentang OJK",
    "Evaluasi": "Kendala utama berada pada hari pelaksanaan acara, sebelum keberangkatan peserta menuju institusi terkait. Adapun kendala tersebut adalah kurang matangnya koordinasi antar divisi terkait alur peserta, mulai dari absensi hingga pembagian konsumsi.",
    "Dokumentasi (Link Drive)": "Dokumentasi Company Visit",
    "Link LPJ": "LPJ comvis"
  },
  {
    "Divisi": "Organizational Development",
    "Nama Proker": "NextGen Empowerment",
    "Tanggal Proker": "2026-03-14",
    "Format Pelaksanaan": "Online",
    "Status": "On Progress",
    "Link Proposal": "Proposal NextGen Empowerment",
    "Deskripsi Proker": "kegiatan NextGen Empowerment dibentuk workshop, simulasi, dan diskusi interaktif membahas aspek teknis maupun strategis pengelolaan organisasi. Adanya kegiatan NextGen Empowerment meningkatkan kemampuan hardskill dan softskill GenBI ITS.",
    "KPI/TUK/Target": "69 orang",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi (Link Drive)": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "Organizational Development",
    "Nama Proker": "Company Visit 2",
    "Tanggal Proker": "Jum'at, 12 Desember 2025",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal Comvis 2",
    "Deskripsi Proker": "Program kerja ini bekerja sama dengan UPN berkunjung PT Kiwoom Sekuritas Indonesia. Sehingga Mahasiswa GenBI (ITS dan UPN) memahami tentang saham",
    "KPI/TUK/Target": "28 Orang",
    "Dampak": "Mahasiswa GenBI (ITS dan UPN) memahami persentase saham tiap bank komersial di Indonesia",
    "Evaluasi": "Secara umum, acara sudah berjalan dengan cukup lancar. Kendala utama berada pada hari pelaksanaan acara, sebelum keberangkatan peserta menuju institusi terkait yang menyebabkan keterlambatan. Adapun kendala tersebut adalah kurang matangnya koordinasi antar divisi terkait alur peserta, mulai dari absensi hingga pembagian konsumsi.",
    "Dokumentasi (Link Drive)": "Dokumentasi GenBI coin",
    "Link LPJ": "LPJ GenBI Coin"
  },
  {
    "Divisi": "Social Environment",
    "Nama Proker": "Edukasi UMKM",
    "Tanggal Proker": "2025-11-27",
    "Format Pelaksanaan": "Offline",
    "Status": "Done",
    "Link Proposal": "Proposal Edukasi UMKM 2025.pdf",
    "Deskripsi Proker": "Sosialisasi terkait QRIS dan CBPR ke pelaku UMKM Kampung Kue, Kecamatan Rungkut, Surabaya. Kegiatan ini diselenggarakan sebagai upaya nyata dalam memperkuat kapasitas dan ketahanan ekonomi pelaku UMKM di tengah era transformasi digital.",
    "KPI/TUK/Target": "Terlaksananya kegiatan Talkshow Edukasi UMKM (Target: 1), Jumlah peserta pelaku usaha (Target: 20), Tingkat kepuasan (Target: 60%)",
    "Dampak": "Meningkatnya keamanan transaksi QRIS, kemampuan teknologi UMKM, pengetahuan Rupiah, dan percepatan transformasi digital.",
    "Evaluasi": "Kegiatan bertabrakan dengan acara lain di Kecamatan Rungkut dan adanya informasi mendadak dari pihak Kampung Kue yang menyebabkan perubahan alur.",
    "Dokumentasi (Link Drive)": "Dokumentasi",
    "Link LPJ": "LPJ EDUKASI UMKM"
  },
  {
    "Divisi": "Social Environment",
    "Nama Proker": "Aksi Lingkungan",
    "Tanggal Proker": "2026-03-04",
    "Format Pelaksanaan": "Offline",
    "Status": "On Progress",
    "Link Proposal": "Proposal Aksi Lingkungan GenBI ITS 2025.docx.pdf",
    "Deskripsi Proker": "Aksi lingkungan berbasis sekolah yang berfokus pada edukasi dan pembangunan sistem sederhana pengelolaan sampah organik melalui pemilahan sampah dan penerapan biopori.",
    "KPI/TUK/Target": "Terlaksananya kegiatan Aksi Lingkungan (Target: 1), Jumlah lubang biopori (Target: 100), Pihak eksternal terlibat (Target: 60)",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi (Link Drive)": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "Social Environment",
    "Nama Proker": "GenBI Mengajar",
    "Tanggal Proker": "2026-02-13",
    "Format Pelaksanaan": "Offline",
    "Status": "On Progress",
    "Link Proposal": "Proposal GenBI Mengajar 2026.pdf",
    "Deskripsi Proker": "Mengunjungi SD di Surabaya untuk mengenalkan ciri keaslian uang Rupiah serta nilai budaya dan pahlawan melalui konsep interaktif permainan dan cerita.",
    "KPI/TUK/Target": "Terlaksananya kegiatan GenBI Mengajar (Target: 1), Jumlah peserta (Target: 60), Tingkat kepuasan (Target: 60%)",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi (Link Drive)": "Menyusul",
    "Link LPJ": "Menyusul"
  },
  {
    "Divisi": "Social Environment",
    "Nama Proker": "Ramadhan Care",
    "Tanggal Proker": "2026-02-28",
    "Format Pelaksanaan": "Offline",
    "Status": "On Progress",
    "Link Proposal": "Proposal Ramadhan Care 2026.pdf",
    "Deskripsi Proker": "Pembagian takjil, santunan anak yatim, dan bantuan warga sekitar kampus ITS untuk menumbuhkan kepedulian sosial anggota GenBI.",
    "KPI/TUK/Target": "Terlaksananya kegiatan Ramadhan Care (Target: 1), Jumlah takjil (Target: 100), Penerima santunan (Target: 20)",
    "Dampak": "Menyusul",
    "Evaluasi": "Menyusul",
    "Dokumentasi (Link Drive)": "Menyusul",
    "Link LPJ": "Menyusul"
  }
];
