import { Router } from 'express';
import multer from 'multer';
import { CmsRole } from '@prisma/client';
import { asyncHandler } from '../middlewares/asyncHandler';
import { requireCmsRole, requireCmsSession } from '../middlewares/cms-session.middleware';
import { createProgram, createProgramRevision, downloadProgramArtifact, listCmsPrograms, previewProgram, previewProgramRevision, transitionProgram, transitionProgramExecution, transitionProgramRevision, updateProgram, uploadProgramArtifact } from '../controllers/program.controller';

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, file.mimetype === 'application/pdf' && file.originalname.toLowerCase().endsWith('.pdf')) });
router.get('/', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_UMUM, CmsRole.SEKRETARIS_DIVISI), asyncHandler(listCmsPrograms));
router.post('/', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(createProgram));
router.post('/preview', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(previewProgram));
router.patch('/:id', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(updateProgram));
router.post('/:id/revisions', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(createProgramRevision));
router.post('/:id/revisions/:revisionId/preview', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI, CmsRole.SEKRETARIS_UMUM), asyncHandler(previewProgramRevision));
router.post('/:id/revisions/:revisionId/transition', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(transitionProgramRevision));
router.post('/:id/transition', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(transitionProgram));
router.post('/:id/execution-transition', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), asyncHandler(transitionProgramExecution));
router.post('/:id/artifacts', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_DIVISI), upload.single('file'), asyncHandler(uploadProgramArtifact));
router.get('/:id/artifacts/:artifactId', requireCmsSession, requireCmsRole(CmsRole.ADMIN_GLOBAL, CmsRole.SEKRETARIS_UMUM, CmsRole.SEKRETARIS_DIVISI), asyncHandler(downloadProgramArtifact));
export default router;
